import * as stylex from '@stylexjs/stylex';
import { colors, motion, radius, spacing, typography } from '../../../lib/stylex/tokens.stylex';

const shimmer = stylex.keyframes({
  '0%': { backgroundPosition: '200% 0' },
  '100%': { backgroundPosition: '-200% 0' },
});

export const dashboardStyles = stylex.create({
  heroGrid: {
    display: 'grid',
    gap: spacing.xxl,
    alignItems: 'stretch',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 960px)': 'minmax(0, 1.65fr) minmax(320px, 0.95fr)',
    },
  },
  commandCard: {
    overflow: 'hidden',
    padding: {
      default: spacing.xxl,
      '@media (min-width: 640px)': '28px',
      '@media (min-width: 1280px)': spacing.xxxl,
    },
    background:
      `radial-gradient(circle at 12% 0%, ${colors.infoSurface}, transparent 36%), radial-gradient(circle at 100% 0%, ${colors.accentMuted}, transparent 30%), linear-gradient(160deg, ${colors.bgElevated}, ${colors.bgPanel})`,
    position: 'relative',
    '::after': {
      content: "''",
      position: 'absolute',
      inset: '1px',
      borderRadius: '22px',
      border: `1px solid ${colors.borderSubtle}`,
      pointerEvents: 'none',
    },
  },
  stationCard: {
    padding: {
      default: spacing.xxl,
      '@media (min-width: 640px)': '28px',
    },
    background:
      `radial-gradient(circle at 80% 0%, ${colors.accentMuted}, transparent 36%), linear-gradient(170deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
  },
  headerRow: {
    display: 'flex',
    alignItems: {
      default: 'flex-start',
      '@media (max-width: 639px)': 'flex-start',
    },
    flexDirection: {
      default: 'row',
      '@media (max-width: 639px)': 'column',
    },
    justifyContent: 'space-between',
    gap: spacing.lg,
  },
  kicker: {
    fontSize: typography.microSize,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: colors.textMuted,
  },
  title: {
    marginTop: '8px',
    fontFamily: typography.display,
    fontSize: 'clamp(1.8rem, 3vw, 2.5rem)',
    lineHeight: 1,
    color: colors.textPrimary,
    letterSpacing: '0.01em',
  },
  lede: {
    marginTop: '18px',
    fontSize: 'clamp(1.05rem, 1.3vw, 1.2rem)',
    lineHeight: 1.5,
    color: colors.textPrimary,
  },
  body: {
    color: colors.textSecondary,
    lineHeight: 1.7,
  },
  commandBody: {
    marginTop: '10px',
    maxWidth: '62ch',
  },
  heroTopRow: {
    display: 'grid',
    gap: spacing.lg,
    alignItems: 'stretch',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 1200px)': 'minmax(0, 1.2fr) minmax(320px, 0.8fr)',
    },
  },
  heroLeadStack: {
    display: 'grid',
    gap: '10px',
  },
  heroStatusRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  heroChipRow: {
    justifyContent: 'flex-end',
  },
  heroChip: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '28px',
    padding: `${spacing.xs} ${spacing.md}`,
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanelAlt,
    color: colors.textMuted,
    fontSize: typography.microSize,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  heroNarrativeCard: {
    padding: spacing.lg,
    borderRadius: radius.xl,
    border: `1px solid ${colors.borderDefault}`,
    background: `linear-gradient(155deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
    boxShadow: colors.shadowInset,
  },
  heroNarrativeHead: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  heroNarrativeKicker: {
    fontSize: typography.microSize,
    lineHeight: typography.microLine,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: colors.textPrimary,
    fontWeight: 700,
  },
  heroNarrativeMeta: {
    color: colors.textMuted,
    fontSize: typography.microSize,
    lineHeight: 1.45,
  },
  heroActionRail: {
    display: 'grid',
    gap: spacing.md,
    padding: spacing.lg,
    borderRadius: radius.xl,
    border: `1px solid ${colors.borderDefault}`,
    background: `linear-gradient(160deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
  },
  heroActionMeta: {
    display: 'grid',
    gap: '4px',
  },
  heroActionKicker: {
    fontSize: '0.72rem',
    lineHeight: 1,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    color: colors.textMuted,
    fontWeight: 700,
  },
  heroActionHint: {
    color: colors.textSecondary,
    lineHeight: 1.55,
    fontSize: typography.bodySize,
  },
  heroActionButtons: {
    display: 'grid',
    gap: '10px',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 640px)': 'repeat(3, minmax(0, 1fr))',
      '@media (min-width: 1200px)': '1fr',
    },
  },
  heroActionButton: {
    width: '100%',
    justifyContent: 'center',
  },
  heroActionButtonGhost: {
    backgroundColor: colors.bgPanel,
    borderColor: colors.borderDefault,
    color: colors.textPrimary,
  },
  stack: {
    display: 'grid',
    gap: spacing.md,
  },
  signalGrid: {
    marginTop: '20px',
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: {
      default: 'repeat(3, minmax(0, 1fr))',
      '@media (max-width: 959px)': '1fr',
    },
  },
  signalCard: {
    padding: `${spacing.md} ${spacing.lg}`,
    display: 'grid',
    gap: spacing.xs,
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanelAlt,
  },
  signalText: {
    color: colors.textMuted,
    fontSize: typography.secondarySize,
  },
  signalLabel: {
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
  },
  emphasis: {
    color: colors.textPrimary,
    fontWeight: 700,
  },
  metricGrid: {
    marginTop: '22px',
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 639px)': '1fr',
    },
  },
  metricTile: {
    padding: `${spacing.md} ${spacing.lg}`,
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanelAlt,
  },
  metricTileActive: {
    borderColor: colors.successBorder,
    background: `linear-gradient(160deg, ${colors.successSurface}, ${colors.bgPanel})`,
  },
  metricTileAlert: {
    borderColor: colors.dangerBorder,
    background: `linear-gradient(160deg, ${colors.dangerSurfaceStrong}, ${colors.bgPanel})`,
  },
  metricValue: {
    fontFamily: typography.display,
    fontSize: typography.metricSize,
    lineHeight: 1,
    color: colors.textPrimary,
  },
  metricLabel: {
    marginTop: '6px',
    color: colors.textSecondary,
    fontSize: typography.secondarySize,
  },
  metricHint: {
    marginTop: '4px',
    color: colors.textMuted,
    fontSize: typography.microSize,
    lineHeight: 1.35,
  },
  heroActionDeckSection: {
    marginTop: spacing.xl,
    display: 'grid',
    gap: spacing.lg,
  },
  heroActionDeckHeader: {
    display: 'grid',
    gap: spacing.sm,
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 960px)': 'minmax(0, 1fr) minmax(280px, 0.72fr)',
    },
    alignItems: 'end',
  },
  heroActionDeckIntro: {
    margin: 0,
  },
  actionDeckGrid: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 720px)': 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 1200px)': 'repeat(3, minmax(0, 1fr))',
    },
  },
  actionDeckCard: {
    display: 'grid',
    gap: spacing.sm,
    minHeight: '100%',
    padding: spacing.lg,
    borderRadius: radius.xl,
    border: `1px solid ${colors.borderDefault}`,
    background: `linear-gradient(160deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
    color: colors.textPrimary,
    textDecoration: 'none',
    transitionProperty: 'transform, border-color, box-shadow, background-color',
    transitionDuration: motion.base,
    transitionTimingFunction: motion.easeStandard,
    boxShadow: colors.shadowInset,
    ':hover': {
      transform: 'translateY(-1px)',
      borderColor: colors.borderStrong,
      boxShadow: colors.shadowCard,
    },
  },
  actionDeckCardActive: {
    borderColor: colors.successBorder,
    background: `linear-gradient(155deg, ${colors.successSurface}, ${colors.bgPanel})`,
  },
  actionDeckCardAlert: {
    borderColor: colors.dangerBorder,
    background: `linear-gradient(155deg, ${colors.dangerSurfaceStrong}, ${colors.bgPanel})`,
  },
  actionDeckHead: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    minWidth: 0,
  },
  actionDeckIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '30px',
    height: '30px',
    borderRadius: radius.md,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanel,
    color: colors.textPrimary,
    flexShrink: 0,
  },
  actionDeckEyebrow: {
    fontSize: typography.microSize,
    lineHeight: typography.microLine,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: colors.textMuted,
    fontWeight: 700,
  },
  actionDeckTitle: {
    color: colors.textPrimary,
    fontSize: typography.titleSize,
    lineHeight: 1.35,
    fontWeight: 700,
  },
  actionDeckBody: {
    color: colors.textSecondary,
    fontSize: typography.secondarySize,
    lineHeight: 1.5,
  },
  actionDeckFooter: {
    marginTop: 'auto',
    color: colors.accentStrong,
    fontSize: typography.microSize,
    lineHeight: 1.2,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    fontWeight: 700,
  },
  stationSummaryRow: {
    marginTop: '14px',
    display: 'grid',
    gap: spacing.lg,
  },
  stationSummaryBody: {
    margin: 0,
  },
  stationQuickLinkRow: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 640px)': 'repeat(2, minmax(0, 1fr))',
    },
  },
  stationChips: {
    marginTop: spacing.lg,
  },
  stationIdentityRow: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
    flexWrap: 'wrap',
    marginTop: spacing.xs,
  },
  stationTitle: {
    marginTop: 0,
    fontSize: 'clamp(1.45rem, 2.2vw, 2rem)',
  },
  stationChip: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '34px',
    padding: '0 12px',
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanel,
    color: colors.textPrimary,
    fontSize: typography.secondarySize,
    fontWeight: 600,
  },
  factsGrid: {
    marginTop: '18px',
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (max-width: 639px)': '1fr',
    },
  },
  factCard: {
    padding: '14px 16px',
    display: 'grid',
    gap: '6px',
    borderRadius: '18px',
    border: '1px solid rgba(85, 119, 138, 0.26)',
    backgroundColor: 'rgba(9, 16, 24, 0.72)',
  },
  queueCard: {
    marginTop: '14px',
    padding: '14px 16px',
    display: 'grid',
    gap: '8px',
    borderRadius: '18px',
    border: '1px solid rgba(85, 119, 138, 0.26)',
    backgroundColor: 'rgba(9, 16, 24, 0.72)',
  },
  queueBadgeText: {
    color: 'rgba(159, 184, 198, 0.88)',
    fontSize: '0.82rem',
  },
  stationNote: {
    color: 'rgba(170, 195, 210, 0.88)',
    fontSize: '0.82rem',
  },
  overlayCard: {
    marginTop: '14px',
    padding: '14px 16px',
    display: 'grid',
    gap: '12px',
    borderRadius: '18px',
    border: '1px solid rgba(85, 119, 138, 0.26)',
    backgroundColor: 'rgba(9, 16, 24, 0.72)',
  },
  primaryGrid: {
    display: 'grid',
    gap: '18px',
    alignItems: 'stretch',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 960px)': 'minmax(0, 0.92fr) minmax(0, 1.08fr)',
    },
  },
  denseLaneGrid: {
    display: 'grid',
    gap: spacing.lg,
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 1180px)': 'repeat(2, minmax(0, 1fr))',
    },
    alignItems: 'start',
  },
  denseLane: {
    display: 'grid',
    gap: spacing.lg,
    padding: {
      default: spacing.lg,
      '@media (min-width: 640px)': spacing.xl,
    },
    borderRadius: radius.xxl,
    border: `1px solid ${colors.borderDefault}`,
    background: `linear-gradient(180deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
    boxShadow: colors.shadowInset,
  },
  denseLaneActive: {
    borderColor: colors.successBorder,
    background: `linear-gradient(180deg, ${colors.successSurface}, ${colors.bgPanel})`,
  },
  denseLaneAlert: {
    borderColor: colors.dangerBorder,
    background: `linear-gradient(180deg, ${colors.dangerSurfaceStrong}, ${colors.bgPanel})`,
  },
  denseLaneHeader: {
    display: 'grid',
    gap: spacing.md,
  },
  denseLaneSignals: {
    rowGap: spacing.xs,
    columnGap: spacing.sm,
  },
  denseLaneSignal: {
    minHeight: '28px',
    padding: `${spacing.xs} ${spacing.md}`,
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanel,
    color: colors.textSecondary,
    fontSize: typography.microSize,
    lineHeight: 1.3,
  },
  denseLaneCards: {
    display: 'grid',
    gap: spacing.md,
  },
  statusCard: {
    minHeight: '100%',
    padding: {
      default: spacing.xl,
      '@media (min-width: 640px)': spacing.xxl,
    },
  },
  statusCardActive: {
    borderColor: colors.successBorder,
  },
  statusCardAlert: {
    borderColor: colors.dangerBorder,
  },
  statusCardFeed: {
    position: 'relative',
    overflow: 'hidden',
    background:
      `radial-gradient(circle at 100% 0%, ${colors.infoSurface}, transparent 38%), linear-gradient(180deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
    gridColumn: {
      default: 'auto',
      '@media (min-width: 960px)': '2',
    },
    gridRow: {
      default: 'auto',
      '@media (min-width: 960px)': '1 / span 2',
    },
  },
  titleWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.md,
  },
  titleIcon: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '36px',
    height: '36px',
    borderRadius: radius.md,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanel,
    color: colors.textPrimary,
  },
  iconGlyphMd: {
    width: '20px',
    height: '20px',
  },
  iconGlyphSm: {
    width: '16px',
    height: '16px',
  },
  statusTitle: {
    color: colors.textPrimary,
    fontSize: typography.titleSize,
    fontWeight: 700,
  },
  inlineLink: {
    color: colors.accentStrong,
    fontSize: typography.secondarySize,
    fontWeight: 600,
    textDecoration: 'underline',
    textDecorationColor: colors.accentEdge,
    textUnderlineOffset: '0.16em',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    ':hover': {
      color: colors.textPrimary,
      textDecorationColor: colors.accentEdgeStrong,
    },
  },
  denseActionRow: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 640px)': 'repeat(2, minmax(0, 1fr))',
    },
  },
  denseActionLink: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '40px',
    padding: `0 ${spacing.lg}`,
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanel,
    color: colors.textPrimary,
    textDecoration: 'none',
    fontSize: typography.secondarySize,
    fontWeight: 600,
    transitionProperty: 'transform, border-color, background-color',
    transitionDuration: motion.fast,
    ':hover': {
      transform: 'translateY(-1px)',
      borderColor: colors.borderStrong,
      backgroundColor: colors.bgHover,
    },
  },
  quickRouteGrid: {
    display: 'grid',
    gap: spacing.md,
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 640px)': 'repeat(2, minmax(0, 1fr))',
    },
  },
  listItem: {
    padding: `${spacing.md} ${spacing.lg}`,
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: {
      default: 'flex-start',
      '@media (max-width: 639px)': 'flex-start',
    },
    flexDirection: {
      default: 'row',
      '@media (max-width: 639px)': 'column',
    },
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanelAlt,
    backdropFilter: 'blur(10px)',
  },
  metaText: {
    color: colors.textMuted,
    fontSize: typography.secondarySize,
  },
  newsSpotlight: {
    padding: `${spacing.md} ${spacing.lg}`,
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanelAlt,
    backdropFilter: 'blur(10px)',
  },
  newsSpotlightFeatured: {
    background:
      `radial-gradient(circle at 100% 0%, ${colors.infoSurface}, transparent 34%), ${colors.bgPanel}`,
  },
  newsSpotlightMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: {
      default: 'center',
      '@media (max-width: 639px)': 'flex-start',
    },
    flexDirection: {
      default: 'row',
      '@media (max-width: 639px)': 'column',
    },
    marginBottom: '8px',
  },
  newsTitle: {
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: '3',
    overflow: 'hidden',
    lineHeight: 1.45,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    color: colors.textPrimary,
    fontWeight: 700,
  },
  activityList: {
    position: 'relative',
    display: 'grid',
    gap: spacing.md,
    '::before': {
      content: "''",
      position: 'absolute',
      top: '10px',
      bottom: '10px',
      left: '18px',
      width: '1px',
      background: `linear-gradient(180deg, ${colors.infoBorder}, transparent)`,
    },
  },
  activityItem: {
    position: 'relative',
    display: 'grid',
    gridTemplateColumns: {
      default: 'auto minmax(0, 1fr) auto',
      '@media (max-width: 639px)': 'auto minmax(0, 1fr)',
    },
    gap: spacing.lg,
    alignItems: 'start',
    padding: `${spacing.md} ${spacing.lg} ${spacing.md} ${spacing.md}`,
    borderRadius: radius.xl,
    border: `1px solid ${colors.borderDefault}`,
    background: `linear-gradient(160deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
    backdropFilter: 'blur(10px)',
  },
  activityItemActive: {
    borderColor: colors.successBorder,
    background: `linear-gradient(160deg, ${colors.successSurface}, ${colors.bgPanel})`,
  },
  activityItemAlert: {
    borderColor: colors.dangerBorder,
    background: `linear-gradient(160deg, ${colors.dangerSurfaceStrong}, ${colors.bgPanel})`,
  },
  activityIcon: {
    position: 'relative',
    zIndex: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '38px',
    height: '38px',
    marginTop: '2px',
    borderRadius: radius.md,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanel,
    color: colors.textPrimary,
    boxShadow: '0 10px 18px rgba(4, 8, 12, 0.28)',
  },
  activityContent: {
    minWidth: 0,
    display: 'grid',
    gap: spacing.xs,
  },
  activityHead: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '8px',
  },
  activityActor: {
    color: colors.textPrimary,
    fontSize: typography.bodySize,
    fontWeight: 700,
    lineHeight: 1.25,
  },
  activityAction: {
    color: colors.textSecondary,
    fontSize: typography.bodySize,
    lineHeight: 1.45,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  activityDetails: {
    color: colors.textSecondary,
    fontSize: typography.secondarySize,
    lineHeight: 1.55,
    padding: `${spacing.sm} ${spacing.md}`,
    borderRadius: radius.md,
    backgroundColor: colors.bgPanel,
    border: `1px solid ${colors.borderSubtle}`,
    maxWidth: '100%',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  activityTime: {
    color: colors.textMuted,
    fontSize: typography.microSize,
    lineHeight: 1.2,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    paddingTop: {
      default: '4px',
      '@media (max-width: 639px)': 0,
    },
    paddingLeft: {
      default: 0,
      '@media (max-width: 639px)': '52px',
    },
  },
  miniSkeleton: {
    display: 'grid',
    gap: '10px',
  },
  miniSkeletonLine: {
    display: 'block',
    height: '14px',
    borderRadius: radius.pill,
    background: 'linear-gradient(90deg, rgba(18, 31, 42, 0.9), rgba(40, 62, 78, 0.9), rgba(18, 31, 42, 0.9))',
    backgroundSize: '200% 100%',
    animationName: shimmer,
    animationDuration: '1.8s',
    animationTimingFunction: 'ease-in-out',
    animationIterationCount: 'infinite',
  },
  miniSkeletonShort: {
    width: '42%',
  },
  miniSkeletonSoft: {
    width: '72%',
  },
  officerEscalationList: {
    display: 'grid',
    gap: '10px',
  },
  officerEscalationItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap',
    color: 'rgba(224, 237, 244, 0.95)',
    lineHeight: 1.5,
  },
  officerEscalationLink: {
    marginLeft: 'auto',
    color: colors.accentStrong,
    fontSize: '0.84rem',
    fontWeight: 600,
    textDecoration: 'underline',
    textUnderlineOffset: '0.16em',
  },
});
