import * as stylex from '@stylexjs/stylex';
import { colors, layout, motion, radius, spacing, typography } from '../../lib/stylex/tokens.stylex';

export const uiStyles = stylex.create({
  sectionShell: {
    scrollMarginTop: 'calc(96px + var(--safe-top))',
    paddingBlock: {
      default: spacing.section,
      '@media (min-width: 640px)': '48px',
      '@media (max-width: 767px)': 'calc(40px + 84px + var(--safe-bottom))',
    },
  },
  sectionContainer: {
    width: '100%',
    maxWidth: layout.container,
    marginInline: 'auto',
    paddingInline: {
      default: spacing.lg,
      '@media (min-width: 640px)': spacing.xxl,
      '@media (min-width: 1024px)': spacing.xxxl,
    },
  },
  stackLg: {
    display: 'grid',
    gap: spacing.xxl,
  },
  stackMd: {
    display: 'grid',
    gap: spacing.lg,
  },
  inlineCenter: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    position: 'relative',
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderSubtle}`,
    background:
      `radial-gradient(circle at 10% 0%, rgba(139, 64, 58, 0.12), transparent 42%), radial-gradient(circle at 88% 10%, ${colors.accentMuted}, transparent 34%), linear-gradient(145deg, ${colors.bgPanel}, ${colors.panelBottom})`,
    transitionProperty: 'border-color, transform, box-shadow',
    transitionDuration: motion.fast,
    boxShadow: colors.shadowCard,
    ':hover': {
      borderColor: colors.borderStrong,
      boxShadow: colors.shadowLifted,
      transform: 'translateY(-1px)',
    },
    ':focus-within': {
      borderColor: colors.accentEdgeStrong,
      boxShadow: `0 0 0 1px ${colors.accentSoft}, 0 24px 44px ${colors.shadowStrong}`,
    },
  },
  sectionCard: {
    borderRadius: radius.xxl,
  },
  softPanel: {
    borderRadius: radius.xl,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanelAlt,
    boxShadow: colors.shadowInset,
  },
  buttonBase: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    textDecoration: 'none',
    borderRadius: radius.md,
    padding: `${spacing.md} ${spacing.xl}`,
    minHeight: '44px',
    fontWeight: 600,
    fontFamily: typography.body,
    fontSize: typography.secondarySize,
    lineHeight: typography.secondaryLine,
    color: colors.textPrimary,
    transitionProperty: 'transform, box-shadow, filter, background, border-color, background-color',
    transitionDuration: motion.fast,
    ':active': {
      transform: 'translateY(1px) scale(0.992)',
    },
    ':focus-visible': {
      outlineOffset: '2px',
    },
    ':disabled': {
      cursor: 'progress',
      opacity: 0.72,
      transform: 'none',
    },
  },
  buttonPrimary: {
    background: `linear-gradient(120deg, ${colors.ember}, ${colors.accent})`,
    border: `1px solid ${colors.accentEdge}`,
    boxShadow: `0 10px 20px ${colors.shadowSoft}`,
    ':hover': {
      background: `linear-gradient(120deg, ${colors.emberStrong}, ${colors.accentStrong})`,
      boxShadow: `0 14px 26px ${colors.shadowStrong}`,
    },
    ':active': {
      filter: 'brightness(0.98)',
    },
    ':focus-visible': {
      outline: `2px solid ${colors.accentEdgeStrong}`,
    },
    ':disabled': {
      boxShadow: `0 10px 20px ${colors.shadowSoft}`,
    },
  },
  buttonSecondary: {
    backgroundColor: colors.bgPanelAlt,
    border: `1px solid ${colors.borderDefault}`,
    boxShadow: colors.shadowInset,
    ':hover': {
      backgroundColor: colors.bgHover,
      borderColor: colors.borderStrong,
      boxShadow: `0 14px 28px ${colors.shadowStrong}`,
    },
    ':active': {
      backgroundColor: colors.bgActive,
    },
    ':focus-visible': {
      outline: `2px solid ${colors.focusRing}`,
    },
  },
  buttonXs: {
    minHeight: '36px',
    padding: '8px 12px',
    fontSize: '0.75rem',
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: '28px',
    padding: `${spacing.xs} ${spacing.md}`,
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderSubtle}`,
    backgroundColor: colors.bgPanelAlt,
    color: colors.textPrimary,
    fontSize: typography.microSize,
    fontWeight: 600,
    lineHeight: 1,
    letterSpacing: '0.04em',
  },
  badgeMuted: {
    color: colors.textMuted,
    backgroundColor: colors.bgPanel,
  },
  badgeSuccess: {
    borderColor: colors.successBorder,
    backgroundColor: colors.successSurface,
    color: colors.successText,
  },
  badgeDanger: {
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerSurface,
    color: 'rgba(254, 202, 202, 0.96)',
  },
  badgeWarning: {
    borderColor: 'rgba(245, 158, 11, 0.28)',
    backgroundColor: 'rgba(120, 53, 15, 0.2)',
    color: 'rgba(253, 230, 138, 0.96)',
  },
  inlineTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    minHeight: '36px',
    padding: `${spacing.sm} ${spacing.lg}`,
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderSubtle}`,
    backgroundColor: colors.bgPanelAlt,
    color: colors.textPrimary,
    fontSize: typography.secondarySize,
    fontWeight: 600,
    cursor: 'pointer',
    transitionProperty: 'border-color, background-color, transform',
    transitionDuration: motion.fast,
    ':hover': {
      borderColor: colors.borderStrong,
      backgroundColor: colors.bgHover,
      transform: 'translateY(-1px)',
    },
  },
  chipActive: {
    borderColor: colors.accentEdgeStrong,
    background: `linear-gradient(135deg, ${colors.accentSoft}, ${colors.accentMuted})`,
    color: colors.paperBright,
    boxShadow: colors.shadowCard,
  },
  iconXs: {
    width: '14px',
    height: '14px',
  },
  iconSm: {
    width: '16px',
    height: '16px',
  },
  iconMd: {
    width: '20px',
    height: '20px',
  },
  iconLg: {
    width: '24px',
    height: '24px',
  },
  iconXl: {
    width: '28px',
    height: '28px',
  },
  icon2xl: {
    width: '40px',
    height: '40px',
  },
  iconMuted: {
    color: colors.textMuted,
  },
  iconAccent: {
    color: colors.accentStrong,
  },
  iconDanger: {
    color: colors.danger,
  },
  iconSuccess: {
    color: colors.success,
  },
  inlineIcon: {
    display: 'inline-block',
    marginRight: spacing.sm,
    verticalAlign: 'text-bottom',
  },
  statusDot: {
    display: 'inline-block',
    width: '8px',
    height: '8px',
    borderRadius: radius.pill,
    backgroundColor: 'currentColor',
    marginRight: spacing.sm,
    opacity: 0.8,
  },
  iconSpin: {
    animationName: 'spin',
    animationDuration: '1s',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
  },
  notice: {
    borderRadius: '16px',
    border: `1px solid ${colors.lineMuted}`,
    backgroundColor: colors.surfaceSoft,
    color: colors.paperStrong,
    fontSize: '0.9rem',
    lineHeight: 1.6,
    padding: '14px 16px',
  },
  noticeSuccess: {
    borderColor: 'rgba(74, 163, 107, 0.42)',
    backgroundColor: 'rgba(12, 45, 28, 0.28)',
    color: 'rgba(190, 241, 207, 0.96)',
  },
  noticeError: {
    borderColor: 'rgba(181, 67, 67, 0.38)',
    backgroundColor: 'rgba(70, 22, 22, 0.22)',
    color: 'rgba(252, 202, 202, 0.96)',
  },
  input: {
    width: '100%',
    borderRadius: radius.md,
    padding: `${spacing.md} ${spacing.lg}`,
    transitionProperty: 'border-color, box-shadow, background-color',
    transitionDuration: motion.fast,
    backgroundColor: colors.bgField,
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textPrimary,
    boxShadow: colors.shadowInset,
    ':focus': {
      outline: 'none',
      borderColor: colors.accentEdgeStrong,
      boxShadow: `0 0 0 3px ${colors.focusGlow}`,
    },
  },
  select: {
    width: '100%',
    borderRadius: radius.md,
    padding: `${spacing.md} ${spacing.lg}`,
    transitionProperty: 'border-color, box-shadow, background-color',
    transitionDuration: motion.fast,
    backgroundColor: colors.bgField,
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textPrimary,
    boxShadow: colors.shadowInset,
    ':focus': {
      outline: 'none',
      borderColor: colors.accentEdgeStrong,
      boxShadow: `0 0 0 3px ${colors.focusGlow}`,
    },
  },
  tableFrame: {
    overflowX: 'auto',
    borderRadius: radius.xl,
    border: `1px solid ${colors.lineMuted}`,
    background: 'linear-gradient(145deg, rgba(17, 19, 24, 0.92), rgba(10, 12, 16, 0.92))',
  },
  textCenter: {
    textAlign: 'center',
  },
  table: {
    minWidth: '100%',
    backgroundColor: 'transparent',
    borderCollapse: 'separate',
    borderSpacing: 0,
  },
  tableHeadCell: {
    padding: '16px 24px',
    textAlign: 'left',
    fontSize: '0.75rem',
    fontWeight: 500,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    position: 'sticky',
    top: 0,
    zIndex: 1,
    backgroundColor: 'rgba(20, 22, 28, 0.95)',
    backdropFilter: 'blur(8px)',
    color: 'rgba(222, 203, 170, 0.92)',
  },
  tableCell: {
    padding: '16px 24px',
    whiteSpace: 'nowrap',
    fontSize: '0.875rem',
    color: '#dccdb2',
    borderTop: '1px solid rgba(255, 255, 255, 0.03)',
  },
  tableRowEven: {
    backgroundColor: 'rgba(20, 22, 28, 0.66)',
  },
  tableRowHover: {
    ':hover': {
      backgroundColor: 'rgba(38, 32, 34, 0.58)',
    },
  },
  modalBackdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 99999,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '16px',
    backgroundColor: 'rgba(7, 8, 12, 0.78)',
    backdropFilter: 'blur(6px)',
  },
  modalShell: {
    position: 'relative',
    width: 'min(100%, 1120px)',
    maxHeight: 'min(92vh, 980px)',
    overflow: 'auto',
    borderRadius: '30px',
    border: '1px solid rgba(160, 139, 103, 0.5)',
    background:
      'radial-gradient(circle at 10% 0%, rgba(169, 71, 63, 0.12), transparent 36%), radial-gradient(circle at 86% 10%, rgba(130, 185, 173, 0.1), transparent 34%), linear-gradient(145deg, rgba(17, 19, 24, 0.97), rgba(10, 12, 16, 0.95))',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.44), inset 0 0 0 1px rgba(248, 237, 217, 0.03)',
  },
  modalShellNarrow: {
    maxWidth: '980px',
  },
  modalShellFull: {
    width: '100%',
    maxWidth: '100%',
    maxHeight: '100%',
    borderRadius: 0,
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '16px',
    marginBottom: '24px',
  },
  modalTitle: {
    fontSize: 'clamp(1.55rem, 3vw, 2rem)',
    fontWeight: 700,
    color: '#e6eff5',
    letterSpacing: '0.01em',
  },
  modalSubtitle: {
    marginTop: '8px',
    color: 'rgba(181, 199, 212, 0.88)',
    fontSize: '0.95rem',
    lineHeight: 1.6,
    maxWidth: '66ch',
  },
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '46px',
    height: '46px',
    borderRadius: '12px',
    backgroundColor: 'rgba(11, 22, 31, 0.84)',
    border: '1px solid rgba(77, 112, 134, 0.46)',
    backdropFilter: 'blur(12px)',
    transitionProperty: 'background-color, border-color, transform, box-shadow',
    transitionDuration: '200ms',
    color: 'inherit',
    textDecoration: 'none',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: 'rgba(18, 35, 48, 0.92)',
      borderColor: 'rgba(151, 194, 216, 0.65)',
      transform: 'translateY(-1px)',
      boxShadow: '0 14px 28px rgba(3, 8, 12, 0.46)',
    },
  },
});
