import * as stylex from '@stylexjs/stylex';
import { themePrimitiveProbeContract, themePrimitives } from '../../lib/stylex/primitives.stylex';
import { colors, layout, motion, radius, spacing, typography } from '../../lib/stylex/tokens.stylex';

export const uiPrimitives = themePrimitives;
export const uiThemeProbeContract = themePrimitiveProbeContract;

export const uiStyles = stylex.create({
  sectionShell: {
    scrollMarginTop: 'calc(96px + var(--safe-top))',
    paddingBlock: {
      default: spacing.section,
      '@media (min-width: 640px)': spacing.sectionLg,
      '@media (max-width: 767px)': 'calc(40px + 84px + var(--safe-bottom))',
    },
  },
  sectionContainer: {
    width: '100%',
    maxWidth: layout.container,
    marginInline: 'auto',
    paddingInline: {
      default: spacing.lg,
      '@media (min-width: 640px)': spacing.xxl,
      '@media (min-width: 1024px)': spacing.xxxl,
    },
  },
  stackLg: {
    display: 'grid',
    gap: spacing.sectionLg,
  },
  stackMd: {
    display: 'grid',
    gap: spacing.lg,
  },
  inlineCenter: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    position: 'relative',
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderSubtle}`,
    background:
      `radial-gradient(circle at 10% 0%, ${colors.surfaceGlowPrimary}, transparent 42%), radial-gradient(circle at 88% 10%, ${colors.surfaceGlowSecondary}, transparent 34%), linear-gradient(145deg, ${colors.surfaceBase}, ${colors.panelBottom})`,
    transitionProperty: 'border-color, transform, box-shadow',
    transitionDuration: motion.fast,
    boxShadow: colors.shadowCard,
    ':hover': {
      borderColor: colors.borderStrong,
      boxShadow: colors.shadowLifted,
      transform: 'translateY(-1px)',
    },
    ':focus-within': {
      borderColor: colors.accentEdgeStrong,
      boxShadow: `0 0 0 1px ${colors.accentSoft}, 0 24px 44px ${colors.shadowStrong}`,
    },
  },
  sectionCard: {
    borderRadius: radius.xxl,
  },
  softPanel: {
    borderRadius: radius.xl,
    border: `1px solid ${colors.borderDefault}`,
    background: `linear-gradient(160deg, ${colors.surfaceRaised}, ${colors.surfaceBase})`,
    boxShadow: colors.shadowInset,
  },
  buttonBase: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    textDecoration: 'none',
    borderRadius: radius.md,
    padding: `${spacing.md} ${spacing.xl}`,
    minHeight: layout.buttonTouchHeight,
    fontWeight: 600,
    fontFamily: typography.body,
    fontSize: typography.secondarySize,
    lineHeight: typography.secondaryLine,
    color: colors.textPrimary,
    transitionProperty: 'transform, box-shadow, filter, background, border-color, background-color',
    transitionDuration: motion.fast,
    ':active': {
      transform: 'translateY(1px) scale(0.992)',
    },
    ':focus-visible': {
      outlineOffset: '2px',
    },
    ':disabled': {
      cursor: 'progress',
      opacity: 0.72,
      transform: 'none',
    },
  },
  buttonPrimary: {
    background: `linear-gradient(120deg, ${colors.buttonPrimaryStart}, ${colors.buttonPrimaryEnd})`,
    border: `1px solid ${colors.accentEdge}`,
    boxShadow: `0 10px 20px ${colors.shadowSoft}`,
    ':hover': {
      background: `linear-gradient(120deg, ${colors.buttonPrimaryHoverStart}, ${colors.buttonPrimaryHoverEnd})`,
      boxShadow: `0 14px 26px ${colors.shadowStrong}`,
    },
    ':active': {
      filter: 'brightness(0.98)',
    },
    ':focus-visible': {
      outline: `2px solid ${colors.accentEdgeStrong}`,
    },
    ':disabled': {
      boxShadow: `0 10px 20px ${colors.shadowSoft}`,
    },
  },
  buttonSecondary: {
    background: `linear-gradient(160deg, ${colors.controlSurface}, ${colors.bgPanelAlt})`,
    border: `1px solid ${colors.borderDefault}`,
    boxShadow: colors.shadowInset,
    ':hover': {
      backgroundColor: colors.controlSurfaceHover,
      borderColor: colors.borderStrong,
      boxShadow: `0 14px 28px ${colors.shadowStrong}`,
    },
    ':active': {
      backgroundColor: colors.controlSurfaceActive,
    },
    ':focus-visible': {
      outline: `2px solid ${colors.focusRing}`,
    },
  },
  buttonXs: {
    minHeight: layout.buttonSecondaryHeight,
    padding: `${spacing.sm} ${spacing.md}`,
    fontSize: typography.secondarySize,
  },
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: layout.badgeHeight,
    padding: `${spacing.xs} ${spacing.md}`,
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderSubtle}`,
    backgroundColor: colors.bgPanelAlt,
    color: colors.textPrimary,
    fontSize: typography.microSize,
    fontWeight: 600,
    lineHeight: 1,
    letterSpacing: '0.04em',
  },
  badgeMuted: {
    color: colors.textMuted,
    backgroundColor: colors.bgPanel,
  },
  badgeSuccess: {
    borderColor: colors.successBorder,
    backgroundColor: colors.successSurface,
    color: colors.successText,
  },
  badgeDanger: {
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerSurface,
    color: colors.dangerText,
  },
  badgeWarning: {
    borderColor: colors.warningBorder,
    backgroundColor: colors.warningSurface,
    color: colors.warningText,
  },
  inlineTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    minHeight: layout.buttonSecondaryHeight,
    padding: `${spacing.sm} ${spacing.lg}`,
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderSubtle}`,
    backgroundColor: colors.bgPanelAlt,
    color: colors.textPrimary,
    fontSize: typography.secondarySize,
    fontWeight: 600,
    cursor: 'pointer',
    transitionProperty: 'border-color, background-color, transform',
    transitionDuration: motion.fast,
    ':hover': {
      borderColor: colors.borderStrong,
      backgroundColor: colors.bgHover,
      transform: 'translateY(-1px)',
    },
  },
  chipActive: {
    borderColor: colors.accentEdgeStrong,
    background: `linear-gradient(135deg, ${colors.accentSoft}, ${colors.accentMuted})`,
    color: colors.paperBright,
    boxShadow: colors.shadowCard,
  },
  iconXs: {
    width: '14px',
    height: '14px',
  },
  iconSm: {
    width: '16px',
    height: '16px',
  },
  iconMd: {
    width: '20px',
    height: '20px',
  },
  iconLg: {
    width: '24px',
    height: '24px',
  },
  iconXl: {
    width: '28px',
    height: '28px',
  },
  icon2xl: {
    width: '40px',
    height: '40px',
  },
  iconMuted: {
    color: colors.textMuted,
  },
  iconAccent: {
    color: colors.accentStrong,
  },
  iconDanger: {
    color: colors.danger,
  },
  iconSuccess: {
    color: colors.success,
  },
  inlineIcon: {
    display: 'inline-block',
    marginRight: spacing.sm,
    verticalAlign: 'text-bottom',
  },
  statusDot: {
    display: 'inline-block',
    width: '8px',
    height: '8px',
    borderRadius: radius.pill,
    backgroundColor: 'currentColor',
    marginRight: spacing.sm,
    opacity: 0.8,
  },
  iconSpin: {
    animationName: 'spin',
    animationDuration: '1s',
    animationTimingFunction: 'linear',
    animationIterationCount: 'infinite',
  },
  notice: {
    borderRadius: radius.lg,
    border: `1px solid ${colors.lineMuted}`,
    backgroundColor: colors.surfaceSoft,
    color: colors.textPrimary,
    fontSize: typography.bodySize,
    lineHeight: typography.bodyLine,
    padding: `${spacing.md} ${spacing.lg}`,
  },
  noticeSuccess: {
    borderColor: colors.successBorder,
    backgroundColor: colors.successSurface,
    color: colors.successText,
  },
  noticeError: {
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerSurfaceStrong,
    color: colors.dangerText,
  },
  input: {
    width: '100%',
    minHeight: layout.fieldHeight,
    borderRadius: radius.md,
    padding: `${spacing.md} ${spacing.lg}`,
    transitionProperty: 'border-color, box-shadow, background-color',
    transitionDuration: motion.fast,
    backgroundColor: colors.controlSurface,
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textPrimary,
    boxShadow: colors.shadowInset,
    ':focus': {
      outline: 'none',
      borderColor: colors.fieldFocusBorder,
      boxShadow: `0 0 0 3px ${colors.focusGlow}`,
      backgroundColor: colors.controlSurfaceHover,
    },
  },
  select: {
    width: '100%',
    minHeight: layout.fieldHeight,
    borderRadius: radius.md,
    padding: `${spacing.md} ${spacing.lg}`,
    transitionProperty: 'border-color, box-shadow, background-color',
    transitionDuration: motion.fast,
    backgroundColor: colors.controlSurface,
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textPrimary,
    boxShadow: colors.shadowInset,
    ':focus': {
      outline: 'none',
      borderColor: colors.fieldFocusBorder,
      boxShadow: `0 0 0 3px ${colors.focusGlow}`,
      backgroundColor: colors.controlSurfaceHover,
    },
  },
  tableFrame: {
    overflowX: 'auto',
    borderRadius: radius.xl,
    border: `1px solid ${colors.lineMuted}`,
    background: `linear-gradient(145deg, ${colors.surfaceBase}, ${colors.controlSurface})`,
  },
  textCenter: {
    textAlign: 'center',
  },
  table: {
    minWidth: '100%',
    backgroundColor: 'transparent',
    borderCollapse: 'separate',
    borderSpacing: 0,
  },
  tableHeadCell: {
    padding: `${spacing.lg} ${spacing.xxl}`,
    textAlign: 'left',
    fontSize: typography.microSize,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    position: 'sticky',
    top: 0,
    zIndex: 1,
    backgroundColor: colors.overlaySurface,
    backdropFilter: 'blur(8px)',
    color: colors.accentStrong,
  },
  tableCell: {
    padding: `${spacing.lg} ${spacing.xxl}`,
    whiteSpace: 'nowrap',
    fontSize: typography.bodySize,
    color: colors.textPrimary,
    borderTop: `1px solid ${colors.lineSoft}`,
  },
  tableRowEven: {
    backgroundColor: colors.controlSurface,
  },
  tableRowHover: {
    ':hover': {
      backgroundColor: colors.controlSurfaceHover,
    },
  },
  modalBackdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 99999,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: colors.overlayScrim,
    backdropFilter: 'blur(6px)',
  },
  modalShell: {
    position: 'relative',
    width: `min(100%, ${layout.overlayWidth})`,
    maxHeight: layout.overlayMaxHeight,
    overflow: 'auto',
    borderRadius: radius.overlay,
    border: `1px solid ${colors.accentEdge}`,
    background:
      `radial-gradient(circle at 10% 0%, ${colors.surfaceGlowPrimary}, transparent 36%), radial-gradient(circle at 86% 10%, ${colors.surfaceGlowSecondary}, transparent 34%), linear-gradient(145deg, ${colors.overlaySurface}, ${colors.surfaceRaised})`,
    boxShadow: `0 20px 40px ${colors.shadowStrong}, inset 0 0 0 1px ${colors.borderSubtle}`,
  },
  modalShellNarrow: {
    maxWidth: layout.overlayWidthNarrow,
  },
  modalShellFull: {
    width: '100%',
    maxWidth: '100%',
    maxHeight: '100%',
    borderRadius: 0,
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.lg,
    marginBottom: spacing.xxl,
  },
  modalTitle: {
    fontSize: 'clamp(1.55rem, 3vw, 2rem)',
    fontWeight: 700,
    color: colors.textPrimary,
    letterSpacing: '0.01em',
  },
  modalSubtitle: {
    marginTop: spacing.sm,
    color: colors.textSecondary,
    fontSize: typography.bodySize,
    lineHeight: typography.bodyLine,
    maxWidth: '66ch',
  },
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: layout.iconButtonSize,
    height: layout.iconButtonSize,
    borderRadius: radius.md,
    backgroundColor: colors.controlSurface,
    border: `1px solid ${colors.borderDefault}`,
    backdropFilter: 'blur(12px)',
    transitionProperty: 'background-color, border-color, transform, box-shadow',
    transitionDuration: motion.base,
    color: 'inherit',
    textDecoration: 'none',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: colors.controlSurfaceHover,
      borderColor: colors.borderStrong,
      transform: 'translateY(-1px)',
      boxShadow: `0 14px 28px ${colors.shadowSoft}`,
    },
  },
});

export const uiThemeProbeStyles = stylex.create({
  rail: {
    position: 'fixed',
    width: '1px',
    height: '1px',
    padding: 0,
    margin: '-1px',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    borderWidth: 0,
    clipPath: 'inset(50%)',
    pointerEvents: 'none',
  },
  stack: {
    display: 'grid',
    gap: spacing.sm,
    width: '320px',
  },
  page: {
    width: '320px',
    minHeight: '180px',
    borderRadius: radius.xl,
    overflow: 'hidden',
  },
  surface: {
    padding: spacing.lg,
  },
  button: {
    width: '100%',
  },
  overlay: {
    width: '320px',
    maxWidth: '320px',
    maxHeight: 'none',
    padding: spacing.lg,
  },
});
