import * as stylex from '@stylexjs/stylex';
import { radius, typography } from '../../../lib/stylex/tokens.stylex';

export const guidesStyles = stylex.create({
  segmented: {
    display: 'inline-flex',
    borderRadius: '20px',
    padding: '6px',
    backgroundColor: 'rgba(11,20,29,0.7)',
    border: '1px solid rgba(34,49,64,0.7)',
    width: 'fit-content',
  },
  segmentedButton: {
    padding: '8px 12px',
    fontSize: '0.875rem',
    borderRadius: '16px',
    transitionProperty: 'background-color, color',
    transitionDuration: '160ms',
    color: 'rgba(156,163,175,0.95)',
    backgroundColor: 'transparent',
  },
  segmentedButtonActive: {
    backgroundColor: 'rgba(24,50,68,0.8)',
    color: '#e6eff5',
  },
  editorFrame: {
    borderRadius: '24px',
    border: '1px solid rgba(34,49,64,0.7)',
    backgroundColor: 'rgba(9,16,25,0.7)',
    padding: {
      default: '16px',
      '@media (min-width: 768px)': '20px',
    },
    display: 'grid',
    gap: '16px',
  },
  toolbarSurface: {
    borderRadius: '20px',
    border: '1px solid rgba(42,60,76,0.72)',
    backgroundColor: 'rgba(12,21,29,0.78)',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.02)',
    padding: '12px',
  },
  previewEmpty: {
    borderRadius: '16px',
    border: '1px dashed #2c4154',
    backgroundColor: 'rgba(11,20,29,0.65)',
    padding: '40px 20px',
    fontSize: '0.875rem',
    color: '#89a2b5',
  },
  subtleNotice: {
    fontSize: '0.875rem',
  },
  actionRow: {
    marginTop: '8px',
    display: 'flex',
    flexDirection: {
      default: 'column',
      '@media (min-width: 640px)': 'row',
    },
    gap: '12px',
    alignItems: {
      default: 'stretch',
      '@media (min-width: 640px)': 'center',
    },
    justifyContent: {
      default: 'flex-start',
      '@media (min-width: 640px)': 'flex-end',
    },
  },
  dropzone: {
    borderRadius: '24px',
    border: '1px dashed rgba(143,185,204,0.35)',
    background: 'linear-gradient(145deg, rgba(10,16,24,0.82), rgba(8,12,18,0.78))',
    padding: '18px 20px',
    transitionProperty: 'border-color, background-color, transform',
    transitionDuration: '160ms',
  },
  dropzoneActive: {
    borderColor: 'rgba(169,209,228,0.65)',
    background: 'linear-gradient(145deg, rgba(20,35,47,0.92), rgba(8,12,18,0.86))',
    transform: 'translateY(-1px)',
  },
  overviewRail: {
    display: 'grid',
    gap: '14px',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 768px)': 'repeat(3, minmax(0, 1fr))',
    },
  },
  overviewCard: {
    display: 'grid',
    gap: '8px',
    padding: '18px 20px',
  },
  overviewKicker: {
    fontSize: '0.72rem',
    lineHeight: 1,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    color: '#8fb9cc',
    fontWeight: 700,
  },
  overviewValue: {
    fontSize: '1.8rem',
    lineHeight: 1,
    fontFamily: typography.display,
    color: '#e6eff5',
  },
  overviewLabel: {
    color: '#b8ccd8',
    fontSize: '0.88rem',
    lineHeight: 1.55,
  },
  commandDeck: {
    display: 'grid',
    gap: '16px',
  },
  filterDeck: {
    display: 'grid',
    gap: '14px',
    borderRadius: '24px',
    border: '1px solid rgba(34,49,64,0.7)',
    backgroundColor: 'rgba(9,16,25,0.74)',
    padding: '18px 20px',
  },
  filterDeckHeader: {
    display: 'flex',
    flexDirection: {
      default: 'column',
      '@media (min-width: 640px)': 'row',
    },
    alignItems: {
      default: 'flex-start',
      '@media (min-width: 640px)': 'center',
    },
    justifyContent: 'space-between',
    gap: '12px',
  },
  dropzoneText: {
    fontSize: '0.875rem',
    color: '#bdd5e4',
  },
  statsText: {
    fontSize: '0.875rem',
    color: '#b8ccd8',
    textAlign: {
      default: 'center',
      '@media (min-width: 640px)': 'left',
    },
  },
  cardGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 768px)': 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 1280px)': 'repeat(3, minmax(0, 1fr))',
    },
    gap: {
      default: '16px',
      '@media (min-width: 640px)': '20px',
    },
  },
  guideCard: {
    textAlign: 'left',
    padding: {
      default: '16px',
      '@media (min-width: 640px)': '20px',
    },
    transitionDuration: '300ms',
  },
  cardTop: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '12px',
  },
  cardTitle: {
    minHeight: {
      default: '3.1rem',
      '@media (min-width: 640px)': '3.5rem',
    },
    marginBottom: '12px',
    fontSize: '1.125rem',
    fontWeight: 700,
    fontFamily: typography.display,
    color: '#e6eff5',
    lineHeight: 1.4,
    letterSpacing: '0.01em',
  },
  cardMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    paddingTop: '12px',
    borderTop: '1px solid rgba(55,65,81,0.5)',
    fontSize: '0.875rem',
    color: 'rgba(156,163,175,0.95)',
  },
  authorPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    borderRadius: '999px',
    backgroundColor: 'rgba(15,23,32,0.7)',
    padding: '4px 12px',
    fontSize: '0.75rem',
    color: '#c5d9e5',
  },
  statPills: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '12px',
    fontSize: '0.75rem',
  },
  statPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    borderRadius: '999px',
    backgroundColor: 'rgba(15,23,32,0.7)',
    padding: '4px 10px',
  },
  commentsRoot: {
    marginTop: '32px',
    display: 'grid',
    gap: '20px',
  },
  commentsHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  commentsTitle: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '1.125rem',
    fontWeight: 700,
    color: '#e6eff5',
  },
  commentsList: {
    display: 'grid',
    gap: '16px',
  },
  commentCard: {
    padding: '20px',
  },
  commentTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '8px',
    fontSize: '0.875rem',
    color: 'rgba(156,163,175,0.95)',
  },
  commentAuthor: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
  },
  commentBody: {
    whiteSpace: 'pre-wrap',
    lineHeight: 1.7,
    color: 'rgba(209,213,219,0.95)',
  },
  moderatorHint: {
    marginTop: '16px',
    fontSize: '0.75rem',
    color: 'rgba(107,114,128,0.95)',
  },
  modalRoot: {
    position: 'fixed',
    inset: 0,
    backgroundColor: '#080c10',
    display: 'flex',
    flexDirection: 'column',
    zIndex: 99999,
  },
  modalHeaderBar: {
    flexShrink: 0,
    backgroundColor: '#0a0e12',
    borderBottom: '1px solid #1a2a38',
    padding: '12px 16px',
  },
  modalHeaderInner: {
    maxWidth: '48rem',
    marginInline: 'auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
  },
  modalTitle: {
    fontSize: '1rem',
    fontWeight: 500,
    color: '#fff',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  modalSubtle: {
    fontSize: '0.75rem',
    color: 'rgba(107,114,128,0.95)',
    marginTop: '2px',
  },
  modalActionRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
  },
  modalContentScroll: {
    flex: 1,
    overflowY: 'auto',
  },
  modalContentWrap: {
    maxWidth: '72rem',
    marginInline: 'auto',
    padding: '24px 16px',
  },
  outlineAside: {
    borderRadius: '24px',
    border: '1px solid #1f3344',
    backgroundColor: 'rgba(11,20,29,0.82)',
    padding: '16px',
    boxShadow: '0 18px 34px rgba(4,8,12,0.35)',
    position: {
      default: 'static',
      '@media (min-width: 1280px)': 'sticky',
    },
    top: {
      default: 'auto',
      '@media (min-width: 1280px)': '24px',
    },
    alignSelf: {
      default: 'auto',
      '@media (min-width: 1280px)': 'start',
    },
  },
  outlineTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '12px',
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#dceaf4',
  },
  outlineList: {
    display: 'grid',
    gap: '6px',
    maxHeight: '70vh',
    overflow: 'auto',
    paddingRight: '4px',
  },
  outlineLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
    textAlign: 'left',
    border: 0,
    backgroundColor: 'transparent',
    color: '#bdd5e4',
    padding: '6px 8px',
    borderRadius: '10px',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: 'rgba(17,31,42,0.9)',
    },
  },
  outlineDot: {
    width: '8px',
    height: '8px',
    borderRadius: '999px',
    backgroundColor: '#8fb9cc',
    flexShrink: 0,
  },
  backlinkCard: {
    display: 'grid',
    gap: '6px',
    textAlign: 'left',
    borderRadius: '18px',
    border: '1px solid #1f3344',
    backgroundColor: 'rgba(11,20,29,0.82)',
    padding: '14px 16px',
    cursor: 'pointer',
  },
  backlinkCategory: {
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
    color: '#8fb9cc',
  },
  backlinkTitle: {
    color: '#e6eff5',
    fontWeight: 600,
  },
  backlinkMeta: {
    fontSize: '0.75rem',
    color: 'rgba(156,163,175,0.95)',
  },
  editorFocusCard: {
    padding: {
      default: '16px',
      '@media (min-width: 768px)': '24px',
    },
  },
  editorBackdrop: {
    zIndex: 100001,
    perspective: 'none',
    transform: 'none',
  },
  editorModalShell: {
    width: '100%',
    maxWidth: '80rem',
    maxHeight: '92vh',
    padding: {
      default: '24px',
      '@media (min-width: 768px)': '32px',
    },
  },
  editorHeaderActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    alignSelf: {
      default: 'flex-start',
      '@media (min-width: 768px)': 'auto',
    },
  },
  modalHeaderLead: {
    minWidth: 0,
    flex: 1,
  },
  modalActionNotice: {
    display: {
      default: 'none',
      '@media (min-width: 640px)': 'inline-flex',
    },
  },
  modalLoadingGrid: {
    display: 'grid',
    gap: '16px',
  },
  modalLoadingCard: {
    display: 'grid',
    gap: '16px',
  },
  modalLoadingStack: {
    marginTop: '16px',
    display: 'grid',
    gap: '12px',
  },
  modalError: {
    color: '#f87171',
  },
  modalMainGrid: {
    display: 'grid',
    gap: '32px',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 1280px)': '260px minmax(0, 1fr)',
    },
  },
  contentStack: {
    display: 'grid',
    gap: '24px',
  },
  backlinksPanel: {
    borderRadius: '24px',
    border: '1px solid #1f3344',
    backgroundColor: 'rgba(11,20,29,0.82)',
    padding: '20px',
    boxShadow: '0 18px 34px rgba(4,8,12,0.35)',
  },
  backlinksHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginBottom: '16px',
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#dceaf4',
  },
  backlinksGrid: {
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 768px)': 'repeat(2, minmax(0, 1fr))',
    },
  },
  commentsSection: {
    marginTop: '32px',
    paddingTop: '24px',
    borderTop: '1px solid #1a2a38',
  },
});
