import * as stylex from '@stylexjs/stylex';
import { radius, typography } from '../../../lib/stylex/tokens.stylex';

export const newsStyles = stylex.create({
  inlineLink: {
    color: 'rgba(168, 219, 241, 0.96)',
    textDecoration: 'underline',
    textDecorationColor: 'rgba(168, 219, 241, 0.52)',
    textUnderlineOffset: '0.18em',
    transitionProperty: 'color, text-decoration-color',
    transitionDuration: '160ms',
    ':hover': {
      color: 'rgba(205, 236, 248, 0.98)',
      textDecorationColor: 'rgba(205, 236, 248, 0.88)',
    },
    ':focus-visible': {
      outline: '2px solid rgba(168, 219, 241, 0.7)',
      outlineOffset: '3px',
      borderRadius: '4px',
    },
  },
  deliveryBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderRadius: radius.pill,
    border: '1px solid rgba(245, 158, 11, 0.28)',
    padding: '4px 10px',
    fontSize: '0.75rem',
  },
  deliveryPending: {
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    color: 'rgba(254, 243, 199, 0.96)',
    borderColor: 'rgba(245, 158, 11, 0.32)',
  },
  deliverySent: {
    backgroundColor: 'rgba(16, 185, 129, 0.12)',
    color: 'rgba(209, 250, 229, 0.96)',
    borderColor: 'rgba(52, 211, 153, 0.32)',
  },
  deliveryFailed: {
    backgroundColor: 'rgba(244, 63, 94, 0.12)',
    color: 'rgba(254, 205, 211, 0.96)',
    borderColor: 'rgba(251, 113, 133, 0.32)',
  },
  sectionGrid: {
    display: 'grid',
    gap: {
      default: '16px',
      '@media (min-width: 640px)': '24px',
    },
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 1280px)': '1.15fr 0.85fr',
    },
  },
  composerCard: {
    padding: {
      default: '20px',
      '@media (min-width: 640px)': '24px',
      '@media (min-width: 768px)': '28px',
    },
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '20px',
  },
  kicker: {
    fontSize: {
      default: '0.75rem',
      '@media (min-width: 640px)': '0.875rem',
    },
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    color: '#9ec5d8',
  },
  panelTitleLg: {
    marginTop: '8px',
    fontSize: '1.5rem',
    fontWeight: 700,
    color: '#cffafe',
    fontFamily: typography.display,
  },
  panelTitleMd: {
    marginTop: '8px',
    fontSize: '1.25rem',
    fontWeight: 700,
    color: '#cffafe',
    fontFamily: typography.display,
  },
  composerGrid: {
    display: 'grid',
    gap: '16px',
  },
  labelStack: {
    display: 'grid',
    gap: '8px',
  },
  label: {
    fontSize: '0.875rem',
    color: 'rgba(156, 163, 175, 0.95)',
  },
  textarea: {
    width: '100%',
    minHeight: '220px',
    resize: 'vertical',
  },
  checkboxWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '12px',
    borderRadius: radius.xl,
    padding: '12px 16px',
    fontSize: '0.875rem',
    color: '#ecfeff',
    border: '1px solid rgba(42, 60, 76, 0.72)',
    backgroundColor: 'rgba(12, 21, 29, 0.78)',
  },
  checkbox: {
    width: '16px',
    height: '16px',
    accentColor: '#67e8f9',
  },
  noticeInfo: {
    borderColor: 'rgba(34, 211, 238, 0.2)',
    backgroundColor: '#11202a',
    color: '#d9edf7',
  },
  actionRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '12px',
  },
  actionHint: {
    fontSize: '0.875rem',
    color: '#c7dbe7',
  },
  previewShell: {
    marginTop: '20px',
    borderRadius: '28px',
    border: '1px solid rgba(34, 211, 238, 0.15)',
    backgroundColor: 'rgba(11, 19, 27, 0.88)',
    padding: '20px',
    boxShadow: '0 24px 60px rgba(2, 8, 14, 0.45)',
  },
  previewShellEmpty: {
    borderStyle: 'dashed',
    borderColor: 'rgba(34, 211, 238, 0.2)',
    backgroundColor: 'rgba(11, 19, 27, 0.78)',
    padding: '24px',
    fontSize: '0.875rem',
    color: 'rgba(156, 163, 175, 0.95)',
  },
  previewTopRow: {
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '0.75rem',
    color: 'rgba(207, 250, 254, 0.7)',
  },
  pinnedPill: {
    borderRadius: radius.pill,
    border: '1px solid rgba(251, 191, 36, 0.3)',
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    padding: '4px 10px',
    color: 'rgba(253, 230, 138, 0.96)',
    fontSize: '0.75rem',
  },
  previewInner: {
    borderRadius: '24px',
    border: '1px solid rgba(34, 211, 238, 0.12)',
    backgroundColor: '#111b24',
    padding: '20px',
  },
  previewTitle: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: '#cffafe',
  },
  previewBody: {
    marginTop: '12px',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'break-word',
    fontSize: '0.875rem',
    lineHeight: 1.75,
    color: 'rgba(229, 231, 235, 0.9)',
  },
  previewAuthor: {
    marginTop: '16px',
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.22em',
    color: 'rgba(107, 114, 128, 0.95)',
  },
  featuredCard: {
    overflow: 'hidden',
    padding: {
      default: '20px',
      '@media (min-width: 640px)': '24px',
      '@media (min-width: 768px)': '32px',
    },
    boxShadow: '0 30px 55px rgba(4, 8, 12, 0.56), 0 0 0 1px rgba(168, 213, 234, 0.1) inset',
  },
  tagRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    marginBottom: '16px',
    fontSize: {
      default: '0.75rem',
      '@media (min-width: 640px)': '0.875rem',
    },
  },
  featuredPinned: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderRadius: radius.pill,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    color: 'rgba(253, 224, 71, 0.96)',
    border: '1px solid rgba(250, 204, 21, 0.3)',
    padding: '4px 10px',
  },
  guildUpdatePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderRadius: radius.pill,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    color: 'rgba(147, 197, 253, 0.96)',
    border: '1px solid rgba(96, 165, 250, 0.2)',
    padding: '4px 10px',
  },
  featuredTitle: {
    marginBottom: '8px',
    fontSize: {
      default: '1.45rem',
      '@media (min-width: 640px)': '1.875rem',
    },
    fontWeight: 700,
    fontFamily: typography.display,
    color: '#cffafe',
    letterSpacing: '0.01em',
  },
  meta: {
    marginBottom: '16px',
    fontSize: '0.78rem',
    lineHeight: 1.2,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: 'rgba(172, 194, 208, 0.82)',
  },
  featuredBody: {
    marginBottom: '24px',
    fontSize: {
      default: '1rem',
      '@media (min-width: 640px)': '1.125rem',
    },
    lineHeight: 1.7,
    color: 'rgba(229, 231, 235, 0.95)',
    overflowWrap: 'break-word',
  },
  expandButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: 0,
    border: 0,
    backgroundColor: 'transparent',
    color: 'rgba(168, 219, 241, 0.94)',
    fontSize: '0.88rem',
    fontWeight: 700,
    letterSpacing: '0.02em',
    transitionProperty: 'color, transform',
    transitionDuration: '160ms',
    marginBottom: '24px',
    cursor: 'pointer',
    ':hover': {
      color: 'rgba(206, 237, 250, 1)',
      transform: 'translateY(-1px)',
    },
    ':focus-visible': {
      outline: '2px solid rgba(139, 185, 204, 0.55)',
      outlineOffset: '4px',
    },
  },
  cardFooter: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    marginTop: 'auto',
    borderTop: '1px solid rgba(34, 211, 238, 0.15)',
    paddingTop: '20px',
  },
  authorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: 'rgba(209, 213, 219, 0.95)',
    fontSize: {
      default: '0.875rem',
      '@media (min-width: 640px)': '1rem',
    },
  },
  actionButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '8px',
  },
  discordLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    borderRadius: '10px',
    border: '1px solid rgba(139, 185, 204, 0.26)',
    backgroundColor: 'rgba(10, 17, 24, 0.7)',
    color: 'rgba(168, 219, 241, 0.94)',
    fontSize: '0.84rem',
    fontWeight: 600,
    textDecoration: 'none',
    transitionProperty: 'border-color, background-color, transform',
    transitionDuration: '160ms',
    ':hover': {
      borderColor: 'rgba(180, 221, 239, 0.55)',
      backgroundColor: 'rgba(15, 27, 37, 0.92)',
      transform: 'translateY(-1px)',
    },
  },
  listGrid: {
    display: 'grid',
    gap: {
      default: '16px',
      '@media (min-width: 640px)': '20px',
    },
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 768px)': 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 1280px)': 'repeat(3, minmax(0, 1fr))',
    },
    alignItems: 'stretch',
  },
  newsCard: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100%',
    padding: {
      default: '20px',
      '@media (min-width: 640px)': '24px',
      '@media (min-width: 768px)': '28px',
    },
  },
  newsCardTitle: {
    marginBottom: '8px',
    fontSize: {
      default: '1.125rem',
      '@media (min-width: 640px)': '1.25rem',
    },
    fontWeight: 700,
    fontFamily: typography.display,
    color: '#a5f3fc',
    letterSpacing: '0.01em',
  },
  previewText: {
    marginBottom: '16px',
    fontSize: {
      default: '0.875rem',
      '@media (min-width: 640px)': '1rem',
    },
    lineHeight: 1.7,
    color: 'rgba(229, 231, 235, 0.95)',
    overflowWrap: 'break-word',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: '5',
    overflow: 'hidden',
  },
  previewExpanded: {
    display: 'block',
    WebkitLineClamp: 'unset',
    overflow: 'visible',
  },
});
