import * as stylex from '@stylexjs/stylex';
import { colors, motion, radius, spacing, typography } from '../../../lib/stylex/tokens.stylex';

export const newsStyles = stylex.create({
  inlineLink: {
    color: colors.accentStrong,
    textDecoration: 'underline',
    textDecorationColor: colors.accentEdge,
    textUnderlineOffset: '0.18em',
    transitionProperty: 'color, text-decoration-color',
    transitionDuration: motion.fast,
    ':hover': {
      color: colors.textPrimary,
      textDecorationColor: colors.accentEdgeStrong,
    },
    ':focus-visible': {
      outline: `2px solid ${colors.focusRing}`,
      outlineOffset: '3px',
      borderRadius: '4px',
    },
  },
  iconMd: {
    width: '20px',
    height: '20px',
  },
  iconSm: {
    width: '16px',
    height: '16px',
  },
  iconXs: {
    width: '14px',
    height: '14px',
  },
  iconState: {
    color: colors.danger,
  },
  iconMuted: {
    color: colors.textMuted,
  },
  iconEmpty: {
    width: '40px',
    height: '40px',
    color: colors.textMuted,
  },
  iconStateMd: {
    width: '24px',
    height: '24px',
    color: colors.danger,
  },
  iconStateLg: {
    width: '28px',
    height: '28px',
    color: colors.danger,
  },
  inlineButtonIconMd: {
    display: 'inline-block',
    width: '20px',
    height: '20px',
    marginRight: spacing.sm,
    verticalAlign: 'text-bottom',
  },
  inlineButtonIconSm: {
    display: 'inline-block',
    width: '16px',
    height: '16px',
    marginRight: spacing.sm,
    verticalAlign: 'text-bottom',
  },
  deliveryBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderRadius: radius.pill,
    border: `1px solid ${colors.warningBorder}`,
    padding: '4px 10px',
    fontSize: typography.microSize,
  },
  deliveryPending: {
    backgroundColor: colors.warningSurface,
    color: colors.warningText,
    borderColor: colors.warningBorder,
  },
  deliverySent: {
    backgroundColor: colors.successSurface,
    color: colors.successText,
    borderColor: colors.successBorder,
  },
  deliveryFailed: {
    backgroundColor: colors.dangerSurface,
    color: colors.dangerText,
    borderColor: colors.dangerBorder,
  },
  sectionGrid: {
    display: 'grid',
    gap: {
      default: '16px',
      '@media (min-width: 640px)': '24px',
    },
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 1280px)': '1.15fr 0.85fr',
    },
  },
  heroActionRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.md,
    justifyContent: {
      default: 'flex-start',
      '@media (min-width: 768px)': 'flex-end',
    },
  },
  overviewRail: {
    display: 'grid',
    gap: spacing.lg,
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 768px)': 'repeat(3, minmax(0, 1fr))',
    },
  },
  overviewCard: {
    display: 'grid',
    gap: spacing.sm,
    padding: `${spacing.lg} ${spacing.xl}`,
  },
  overviewValue: {
    fontSize: '1.8rem',
    lineHeight: 1,
    color: colors.textPrimary,
    fontFamily: typography.display,
  },
  overviewLabel: {
    color: colors.textSecondary,
    lineHeight: 1.55,
    fontSize: typography.bodySize,
  },
  composerCard: {
    padding: {
      default: '20px',
      '@media (min-width: 640px)': '24px',
      '@media (min-width: 768px)': '28px',
    },
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: '20px',
  },
  kicker: {
    fontSize: {
      default: '0.75rem',
      '@media (min-width: 640px)': typography.secondarySize,
    },
    textTransform: 'uppercase',
    letterSpacing: '0.18em',
    color: colors.textMuted,
  },
  panelTitleLg: {
    marginTop: '8px',
    fontSize: '1.5rem',
    fontWeight: 700,
    color: colors.textPrimary,
    fontFamily: typography.display,
  },
  panelTitleMd: {
    marginTop: '8px',
    fontSize: '1.25rem',
    fontWeight: 700,
    color: colors.textPrimary,
    fontFamily: typography.display,
  },
  composerGrid: {
    display: 'grid',
    gap: '16px',
  },
  labelStack: {
    display: 'grid',
    gap: '8px',
  },
  label: {
    fontSize: '0.875rem',
    color: 'rgba(198, 187, 168, 0.95)',
  },
  textarea: {
    width: '100%',
    minHeight: '220px',
    resize: 'vertical',
  },
  checkboxWrap: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '12px',
    borderRadius: radius.xl,
    padding: '12px 16px',
    fontSize: '0.875rem',
    color: colors.textPrimary,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanelAlt,
  },
  checkbox: {
    width: '16px',
    height: '16px',
    accentColor: colors.accent,
  },
  noticeInfo: {
    borderColor: colors.accentEdge,
    backgroundColor: colors.bgPanel,
    color: colors.textPrimary,
  },
  actionRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '12px',
  },
  actionHint: {
    fontSize: typography.bodySize,
    color: colors.textSecondary,
  },
  previewShell: {
    marginTop: '20px',
    borderRadius: radius.xxl,
    border: `1px solid ${colors.borderSubtle}`,
    backgroundColor: colors.bgPanel,
    padding: spacing.xl,
    boxShadow: '0 16px 34px rgba(2, 8, 14, 0.32)',
  },
  previewShellEmpty: {
    borderStyle: 'dashed',
    borderColor: colors.borderSubtle,
    backgroundColor: colors.bgPanelAlt,
    padding: spacing.xxl,
    fontSize: typography.bodySize,
    color: colors.textMuted,
  },
  previewTopRow: {
    marginBottom: '12px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '0.75rem',
    color: colors.textMuted,
  },
  pinnedPill: {
    borderRadius: radius.pill,
    border: `1px solid ${colors.warningBorder}`,
    backgroundColor: colors.warningSurface,
    padding: '4px 10px',
    color: colors.warningText,
    fontSize: typography.microSize,
  },
  previewInner: {
    borderRadius: radius.xxl,
    border: `1px solid ${colors.borderSubtle}`,
    backgroundColor: colors.bgPanelAlt,
    padding: spacing.xl,
  },
  previewTitle: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: colors.textPrimary,
  },
  previewBody: {
    marginTop: '12px',
    whiteSpace: 'pre-wrap',
    overflowWrap: 'break-word',
    fontSize: typography.bodySize,
    lineHeight: 1.75,
    color: colors.textSecondary,
  },
  previewAuthor: {
    marginTop: '16px',
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.22em',
    color: colors.textMuted,
  },
  featuredCard: {
    overflow: 'hidden',
    width: '100%',
    maxWidth: '960px',
    marginInline: 'auto',
    padding: {
      default: '20px',
      '@media (min-width: 640px)': '24px',
      '@media (min-width: 768px)': '32px',
    },
    boxShadow: `0 18px 34px ${colors.shadowSoft}, 0 0 0 1px ${colors.borderSubtle} inset`,
  },
  tagRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexWrap: 'wrap',
    marginBottom: '16px',
    fontSize: {
      default: '0.75rem',
      '@media (min-width: 640px)': '0.875rem',
    },
  },
  tagRowCompact: {
    marginBottom: 0,
  },
  cardHeaderRail: {
    display: 'flex',
    alignItems: {
      default: 'flex-start',
      '@media (max-width: 639px)': 'flex-start',
    },
    justifyContent: 'space-between',
    gap: '12px',
    flexDirection: {
      default: 'row',
      '@media (max-width: 639px)': 'column',
    },
    marginBottom: '10px',
  },
  featuredPinned: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderRadius: radius.pill,
    backgroundColor: colors.warningSurface,
    color: colors.warningText,
    border: `1px solid ${colors.warningBorder}`,
    padding: '4px 10px',
  },
  guildUpdatePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    borderRadius: radius.pill,
    backgroundColor: colors.accentMuted,
    color: colors.accentStrong,
    border: `1px solid ${colors.accentEdge}`,
    padding: '4px 10px',
  },
  featuredTitle: {
    marginBottom: '8px',
    fontSize: {
      default: '1.45rem',
      '@media (min-width: 640px)': '1.875rem',
    },
    fontWeight: 700,
    fontFamily: typography.display,
    color: colors.textPrimary,
    letterSpacing: '0.01em',
  },
  meta: {
    marginBottom: '16px',
    fontSize: '0.78rem',
    lineHeight: 1.2,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: colors.textMuted,
  },
  featuredBody: {
    marginBottom: '24px',
    fontSize: {
      default: '1rem',
      '@media (min-width: 640px)': '1.125rem',
    },
    lineHeight: 1.7,
    color: colors.textSecondary,
    overflowWrap: 'break-word',
  },
  expandButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: 0,
    border: 0,
    backgroundColor: 'transparent',
    color: colors.accentStrong,
    fontSize: '0.88rem',
    fontWeight: 700,
    letterSpacing: '0.02em',
    transitionProperty: 'color, transform',
    transitionDuration: motion.fast,
    marginBottom: '24px',
    cursor: 'pointer',
    ':hover': {
      color: colors.textPrimary,
      transform: 'translateY(-1px)',
    },
    ':focus-visible': {
      outline: `2px solid ${colors.focusRing}`,
      outlineOffset: '4px',
    },
  },
  cardFooter: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
    marginTop: 'auto',
    borderTop: `1px solid ${colors.borderSubtle}`,
    paddingTop: '20px',
  },
  authorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: colors.textSecondary,
    fontSize: {
      default: '0.875rem',
      '@media (min-width: 640px)': '1rem',
    },
  },
  actionButtons: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '8px',
  },
  discordLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: `${spacing.sm} ${spacing.md}`,
    borderRadius: radius.sm,
    border: `1px solid ${colors.accentEdge}`,
    backgroundColor: colors.bgPanel,
    color: colors.accentStrong,
    fontSize: typography.secondarySize,
    fontWeight: 600,
    textDecoration: 'none',
    transitionProperty: 'border-color, background-color, transform',
    transitionDuration: motion.fast,
    ':hover': {
      borderColor: colors.accentEdgeStrong,
      backgroundColor: colors.bgHover,
      transform: 'translateY(-1px)',
    },
  },
  listGrid: {
    display: 'grid',
    gap: {
      default: '16px',
        '@media (min-width: 640px)': spacing.xl,
    },
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 768px)': 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 1280px)': 'repeat(3, minmax(0, 1fr))',
    },
    alignItems: 'stretch',
  },
  newsCard: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100%',
    padding: {
      default: spacing.xl,
      '@media (min-width: 640px)': spacing.xxl,
      '@media (min-width: 768px)': '28px',
    },
  },
  newsCardTitle: {
    marginBottom: '8px',
    fontSize: {
      default: '1.125rem',
      '@media (min-width: 640px)': '1.25rem',
    },
    fontWeight: 700,
    fontFamily: typography.display,
    color: colors.textPrimary,
    letterSpacing: '0.01em',
  },
  previewText: {
    marginBottom: '16px',
    fontSize: {
      default: '0.875rem',
      '@media (min-width: 640px)': '1rem',
    },
    lineHeight: 1.7,
    color: colors.textSecondary,
    overflowWrap: 'break-word',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: '5',
    overflow: 'hidden',
  },
  previewExpanded: {
    display: 'block',
    WebkitLineClamp: 'unset',
    overflow: 'visible',
  },
});
