import * as stylex from '@stylexjs/stylex';
import { radius, typography } from '../../lib/stylex/tokens.stylex';

export const analyticsStyles = stylex.create({
  card: {
    padding: '24px',
    display: 'grid',
    gap: '16px',
  },
  empty: {
    textAlign: 'center',
    paddingBlock: '32px',
    color: 'rgba(156,163,175,0.95)',
  },
  emptyText: {
    fontSize: '0.875rem',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  title: {
    fontSize: '0.95rem',
    fontWeight: 700,
    color: '#d7e9f2',
    letterSpacing: '0.01em',
  },
  meta: {
    fontSize: '0.75rem',
    color: 'rgba(156,163,175,0.95)',
  },
  subtleRow: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '12px',
    fontSize: '0.75rem',
  },
  grid2: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 768px)': 'repeat(2, minmax(0, 1fr))',
    },
    gap: '16px',
  },
  grid3: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: '8px',
    fontSize: '0.75rem',
  },
  summaryGrid4: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 768px)': 'repeat(4, minmax(0, 1fr))',
    },
    gap: '16px',
    paddingTop: '16px',
    borderTop: '1px solid rgba(42,60,76,0.6)',
    fontSize: '0.75rem',
  },
  summaryGrid3: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 768px)': 'repeat(3, minmax(0, 1fr))',
    },
    gap: '16px',
    paddingTop: '16px',
    borderTop: '1px solid rgba(42,60,76,0.6)',
    fontSize: '0.75rem',
  },
  summaryLabel: {
    marginBottom: '4px',
    color: 'rgba(156,163,175,0.95)',
  },
  summaryValue: {
    fontSize: '1.125rem',
    fontWeight: 700,
    color: '#e6eff5',
  },
  summaryValueGood: { color: '#6fb98f' },
  summaryValueWarn: { color: '#b9a56f' },
  summaryValueBad: { color: '#b96f6f' },
  personCard: {
    borderRadius: radius.md,
    border: '1px solid rgba(42,60,76,0.6)',
    backgroundColor: 'rgba(16,26,35,0.65)',
    padding: '16px',
    transitionProperty: 'border-color, background-color',
    transitionDuration: '160ms',
    ':hover': {
      borderColor: 'rgba(47,110,141,0.5)',
    },
  },
  personHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '12px',
  },
  avatar: {
    width: '32px',
    height: '32px',
    borderRadius: radius.pill,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(to bottom right, #2d5a3f, #1a3a2f)',
    color: '#e6eff5',
    fontSize: '0.75rem',
    fontWeight: 700,
  },
  personName: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#e6eff5',
  },
  personRole: {
    fontSize: '0.75rem',
    color: 'rgba(156,163,175,0.95)',
  },
  label: {
    fontSize: '0.75rem',
    color: 'rgba(156,163,175,0.95)',
  },
  statBox: {
    textAlign: 'center',
    padding: '8px',
    borderRadius: '10px',
    backgroundColor: 'rgba(26,42,58,0.6)',
  },
  statBoxValue: {
    fontSize: '0.95rem',
    fontWeight: 700,
    color: '#e6eff5',
  },
  progressTrack: {
    height: '8px',
    borderRadius: radius.pill,
    backgroundColor: 'rgba(26,42,58,0.8)',
    overflow: 'hidden',
  },
  progressFillGood: { background: 'linear-gradient(to right, #2d5a3f, #6fb98f)' },
  progressFillWarn: { background: 'linear-gradient(to right, #5a4a2d, #ffd888)' },
  progressFillBad: { background: 'linear-gradient(to right, #5a2d2d, #b96f6f)' },
  legend: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    fontSize: '0.75rem',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    color: 'rgba(156,163,175,0.95)',
  },
  swatch: {
    width: '12px',
    height: '12px',
    borderRadius: '4px',
  },
  heatmapWrap: {
    overflowX: 'auto',
  },
  heatmapInner: { minWidth: 'max-content' },
  heatmapHeader: {
    display: 'grid',
    gridTemplateColumns: '120px repeat(8, 1fr)',
    gap: '4px',
    marginBottom: '8px',
    fontSize: '0.75rem',
    color: 'rgba(156,163,175,0.95)',
  },
  heatmapRow: {
    display: 'grid',
    gridTemplateColumns: '120px repeat(8, 1fr)',
    gap: '4px',
    marginBottom: '8px',
    alignItems: 'center',
  },
  heatmapCellBase: {
    height: '32px',
    borderRadius: '8px',
    position: 'relative',
    borderWidth: '1px',
    borderStyle: 'solid',
  },
  heatmapCellExcellent: { backgroundColor: 'rgba(45,90,63,0.9)', borderColor: '#2d5a3f' },
  heatmapCellGood: { backgroundColor: 'rgba(90,74,45,0.9)', borderColor: '#5a4a2d' },
  heatmapCellMid: { backgroundColor: 'rgba(90,58,45,0.9)', borderColor: '#5a3a2d' },
  heatmapCellLow: { backgroundColor: 'rgba(90,45,45,0.9)', borderColor: '#5a2d2d' },
  heatmapCellEmpty: { backgroundColor: 'rgba(45,58,90,0.9)', borderColor: '#2d3a5a' },
  heatmapPct: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    fontWeight: 600,
    color: 'rgba(255,255,255,0.9)',
  },
  chartBox: {
    position: 'relative',
    height: '192px',
    marginBottom: '16px',
  },
  chartGrid: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    fontSize: '0.75rem',
    color: 'rgba(107,114,128,0.95)',
  },
  chartBars: {
    position: 'absolute',
    insetBlock: 0,
    left: '40px',
    right: 0,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: '4px',
    paddingInline: '8px',
  },
  chartBarWrap: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    position: 'relative',
  },
  chartBarGood: { background: 'linear-gradient(to top, #2d5a3f, #6fb98f)' },
  chartBarBad: { background: 'linear-gradient(to top, #5a2d2d, #b96f6f)' },
  chartBar: {
    width: '100%',
    borderTopLeftRadius: '8px',
    borderTopRightRadius: '8px',
  },
  xAxis: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '4px',
    paddingInline: '8px',
    marginTop: '8px',
    fontSize: '0.75rem',
    color: 'rgba(156,163,175,0.95)',
  },
  distributionBar: {
    height: '16px',
    borderRadius: radius.pill,
    overflow: 'hidden',
    display: 'flex',
    marginBottom: '24px',
    backgroundColor: 'rgba(16,26,35,0.6)',
  },
  classRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '12px',
    borderRadius: radius.md,
    backgroundColor: 'rgba(16,26,35,0.65)',
    border: '1px solid rgba(42,60,76,0.6)',
  },
  classRowMain: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flex: 1,
    minWidth: 0,
  },
  percentTrack: {
    width: '96px',
    height: '8px',
    borderRadius: radius.pill,
    overflow: 'hidden',
    backgroundColor: 'rgba(26,42,58,0.8)',
  },
  percentFill: { background: 'linear-gradient(to right, #2d5a3f, #6fb98f)', height: '100%' },
});
