import * as stylex from '@stylexjs/stylex';
import { colors, layout, motion, radius, spacing, typography } from '../../lib/stylex/tokens.stylex';

export const shellStyles = stylex.create({
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 40,
    overflow: 'visible',
    background:
      'radial-gradient(circle at 10% 10%, rgba(139, 64, 58, 0.1), transparent 36%), radial-gradient(circle at 88% 12%, rgba(201, 168, 106, 0.1), transparent 40%), linear-gradient(112deg, rgba(20, 18, 24, 0.96), rgba(25, 22, 29, 0.95), rgba(20, 18, 24, 0.96))',
    borderBottom: `1px solid ${colors.accentEdge}`,
    boxShadow: '0 10px 24px rgba(2, 3, 5, 0.52)',
    backdropFilter: 'blur(12px)',
    paddingTop: 'var(--safe-top)',
    paddingLeft: 'var(--safe-left)',
    paddingRight: 'var(--safe-right)',
  },
  headerCompact: {
    boxShadow: '0 8px 18px rgba(2, 3, 5, 0.46)',
  },
  headerPanel: {
    position: 'relative',
    width: '100%',
    maxWidth: layout.shellContainer,
    marginInline: 'auto',
    paddingInline: {
      default: spacing.lg,
      '@media (min-width: 640px)': spacing.xxl,
    },
    paddingTop: {
      default: '12px',
      '@media (min-width: 640px)': '14px',
    },
    paddingBottom: {
      default: '12px',
      '@media (min-width: 640px)': '14px',
    },
    '::after': {
      content: "''",
      position: 'absolute',
      inset: 0,
      borderRadius: radius.xl,
      border: '1px solid rgba(192, 167, 121, 0.14)',
      pointerEvents: 'none',
    },
  },
  headerPanelCompact: {
    paddingTop: '10px',
    paddingBottom: '10px',
  },
  headerTop: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: {
      default: 'center',
      '@media (min-width: 768px)': 'flex-start',
    },
    justifyContent: 'space-between',
    columnGap: spacing.lg,
    rowGap: spacing.md,
  },
  toolbarShell: {
    display: 'grid',
    justifyItems: 'end',
    gap: spacing.sm,
    width: {
      default: 'auto',
      '@media (min-width: 768px)': 'min(100%, 460px)',
    },
  },
  desktopSectionSignal: {
    display: 'none',
    '@media (min-width: 960px)': {
      display: 'grid',
      gap: spacing.xs,
      minWidth: '220px',
      alignSelf: 'stretch',
      alignContent: 'center',
      padding: '14px 16px',
      borderRadius: radius.xl,
      border: `1px solid ${colors.borderSubtle}`,
      background:
        `radial-gradient(circle at 100% 0%, ${colors.infoSurface}, transparent 34%), linear-gradient(155deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
      boxShadow: `inset 0 1px 0 rgba(238, 232, 218, 0.03), 0 14px 24px ${colors.shadowSoft}`,
    },
  },
  desktopSectionSignalCompact: {
    '@media (min-width: 960px)': {
      padding: '12px 14px',
      gap: '2px',
    },
  },
  desktopSectionSignalKicker: {
    fontSize: '0.68rem',
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: colors.paperMuted,
    fontWeight: 700,
  },
  desktopSectionSignalValue: {
    fontFamily: typography.display,
    fontSize: '1.15rem',
    lineHeight: 1,
    color: colors.paperBright,
    letterSpacing: '0.02em',
  },
  desktopSectionSignalMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    flexWrap: 'wrap',
    marginTop: spacing.xs,
  },
  desktopSectionSignalStat: {
    display: 'inline-flex',
    alignItems: 'baseline',
    gap: spacing.xs,
  },
  desktopSectionSignalStatLabel: {
    fontSize: typography.microSize,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: colors.textMuted,
  },
  desktopSectionSignalStatValue: {
    fontSize: typography.secondarySize,
    fontWeight: 700,
    color: colors.paperStrong,
  },
  desktopSectionSignalDivider: {
    width: '1px',
    height: '16px',
    backgroundColor: colors.lineMuted,
  },
  brandBlock: {
    display: 'flex',
    minWidth: 0,
    flex: '1 1 360px',
    alignItems: {
      default: 'flex-start',
      '@media (min-width: 640px)': 'center',
    },
    gap: {
      default: '12px',
      '@media (min-width: 640px)': '16px',
    },
    textAlign: 'left',
    paddingRight: '12px',
    color: 'inherit',
    textDecoration: 'none',
  },
  brandSealWrap: {
    position: 'relative',
    flexShrink: 0,
  },
  brandStatusDot: {
    position: 'absolute',
    top: '-4px',
    right: '-4px',
    display: {
      default: 'none',
      '@media (min-width: 640px)': 'block',
    },
    width: '16px',
    height: '16px',
    borderRadius: radius.pill,
    backgroundColor: '#82b9ad',
    border: '2px solid #13161c',
  },
  sealRing: {
    position: 'relative',
    display: 'grid',
    placeItems: 'center',
    width: {
      default: '46px',
      '@media (min-width: 640px)': '56px',
    },
    height: {
      default: '46px',
      '@media (min-width: 640px)': '56px',
    },
    borderRadius: radius.pill,
    background: `radial-gradient(circle, ${colors.accentMuted}, transparent 65%)`,
    border: `1px solid ${colors.accentEdge}`,
    boxShadow: `inset 0 0 12px ${colors.accentGlow}, 0 0 12px rgba(184, 160, 111, 0.08)`,
    '::after': {
      content: "''",
      position: 'absolute',
      inset: '-6px',
      borderRadius: radius.pill,
      border: '1px dashed rgba(184, 160, 111, 0.28)',
      animationName: 'sigilRotate',
      animationDuration: '22s',
      animationTimingFunction: 'linear',
      animationIterationCount: 'infinite',
    },
  },
  sealCore: {
    width: '40px',
    height: '40px',
    borderRadius: radius.pill,
    background: `linear-gradient(140deg, ${colors.ember}, ${colors.accent})`,
    boxShadow: '0 0 10px rgba(139, 64, 58, 0.22)',
    display: 'grid',
    placeItems: 'center',
  },
  compactSeal: {
    transform: 'scale(0.92)',
  },
  brandTextWrap: {
    minWidth: 0,
    textAlign: 'left',
    display: 'grid',
  },
  brandTitle: {
    margin: 0,
    fontSize: {
      default: '1.45rem',
      '@media (min-width: 640px)': '1.35rem',
    },
    fontWeight: 700,
    fontFamily: typography.display,
    lineHeight: 1,
  },
  brandTitleGlow: {
    color: colors.textPrimary,
    textShadow: '0 10px 24px rgba(2, 3, 5, 0.42)',
  },
  brandSubtitle: {
    display: {
      default: 'none',
      '@media (min-width: 520px)': 'block',
    },
    marginTop: '4px',
    fontSize: {
      default: '0.7rem',
      '@media (min-width: 640px)': '0.8rem',
    },
    color: colors.textSecondary,
    fontFamily: typography.body,
    lineHeight: 1.35,
    whiteSpace: {
      default: 'normal',
      '@media (min-width: 640px)': 'nowrap',
    },
  },
  headerOath: {
    display: {
      default: 'none',
      '@media (min-width: 640px)': 'flex',
    },
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '8px',
    marginTop: '8px',
  },
  headerOathCompact: {
    display: 'none',
  },
  mobileSectionTag: {
    marginTop: '8px',
    display: {
      default: 'block',
      '@media (min-width: 640px)': 'none',
    },
  },
  tag: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    borderRadius: radius.pill,
    border: '1px solid rgba(143, 185, 204, 0.45)',
    background: 'linear-gradient(120deg, rgba(12, 18, 26, 0.85), rgba(14, 22, 32, 0.9))',
    color: colors.accent,
    fontSize: '0.75rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    boxShadow: 'inset 0 0 12px rgba(143, 185, 204, 0.15)',
  },
  tagCompact: {
    letterSpacing: '0.04em',
    textTransform: 'none',
    padding: '6px 10px',
    maxWidth: 'min(520px, 100%)',
  },
  tagText: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  utilityMeta: {
    display: 'grid',
    gap: '4px',
    minWidth: 0,
    paddingInline: spacing.xs,
  },
  utilityPanel: {
    position: 'relative',
    display: 'grid',
    gap: spacing.sm,
    width: '100%',
    padding: spacing.sm,
    borderRadius: radius.xxl,
    background:
      `radial-gradient(circle at 100% 0%, ${colors.accentMuted}, transparent 34%), linear-gradient(160deg, ${colors.bgPanelAlt}, ${colors.bgPanel})`,
    border: `1px solid ${colors.borderSubtle}`,
    boxShadow: `inset 0 1px 0 rgba(238, 232, 218, 0.03), 0 14px 28px ${colors.shadowSoft}`,
    overflow: 'hidden',
    '::after': {
      content: "''",
      position: 'absolute',
      inset: 0,
      borderRadius: radius.xxl,
      border: `1px solid ${colors.accentMuted}`,
      opacity: 0.6,
      pointerEvents: 'none',
    },
  },
  utilityPanelCompact: {
    gap: spacing.xs,
    padding: '6px',
  },
  utilityKicker: {
    fontSize: '0.68rem',
    fontWeight: 700,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    color: colors.paperMuted,
  },
  utilityCurrent: {
    fontSize: '0.78rem',
    color: colors.paperStrong,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  toolbar: {
    display: 'flex',
    width: '100%',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: {
      default: 'flex-end',
      '@media (min-width: 768px)': 'space-between',
    },
    gap: spacing.sm,
    padding: spacing.sm,
    borderRadius: radius.xl,
    background: `linear-gradient(135deg, ${colors.bgField}, rgba(16, 18, 24, 0.98))`,
    border: `1px solid ${colors.borderDefault}`,
    boxShadow: `inset 0 1px 0 rgba(238, 232, 218, 0.03)`,
  },
  toolbarCluster: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  toolbarClusterAdaptive: {
    minWidth: 0,
    justifyContent: {
      default: 'flex-end',
      '@media (min-width: 768px)': 'flex-start',
    },
  },
  toolbarCompact: {
    padding: '6px',
  },
  select: {
    minWidth: '74px',
    flex: {
      default: '1 1 0%',
      '@media (min-width: 640px)': '0 0 auto',
    },
    borderRadius: radius.md,
    padding: '8px 10px',
    fontSize: '0.875rem',
    fontWeight: 500,
    minHeight: '40px',
    backgroundColor: colors.bgField,
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textPrimary,
    backdropFilter: 'blur(8px)',
    transitionProperty: 'background-color, border-color, transform, box-shadow',
    transitionDuration: motion.fast,
    ':focus-visible': {
      outline: `2px solid ${colors.focusRing}`,
      outlineOffset: '2px',
    },
  },
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '8px',
    minWidth: '40px',
    minHeight: '40px',
    borderRadius: radius.md,
    backgroundColor: colors.bgField,
    border: `1px solid ${colors.borderDefault}`,
    backdropFilter: 'blur(8px)',
    transitionProperty: 'background-color, border-color, transform, box-shadow',
    transitionDuration: motion.fast,
    color: 'inherit',
    textDecoration: 'none',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: 'rgba(32, 28, 30, 0.9)',
      borderColor: 'rgba(214, 190, 152, 0.52)',
      transform: 'translateY(-1px)',
      boxShadow: '0 10px 20px rgba(2, 3, 5, 0.36)',
    },
  },
  iconButtonActive: {
    borderColor: 'rgba(236, 218, 185, 0.62)',
    boxShadow: '0 12px 24px rgba(2, 3, 5, 0.44)',
  },
  iconButtonAccent: {
    background: 'linear-gradient(130deg, rgba(139, 64, 58, 0.86), rgba(184, 160, 111, 0.58))',
    border: '1px solid rgba(216, 192, 154, 0.46)',
    boxShadow: '0 10px 20px rgba(2, 3, 5, 0.42)',
    ':hover': {
      background: 'linear-gradient(130deg, rgba(158, 73, 67, 0.9), rgba(198, 175, 126, 0.62))',
      borderColor: 'rgba(239, 220, 190, 0.62)',
    },
  },
  themeToggleGroup: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '4px',
    borderRadius: '14px',
    background: 'linear-gradient(135deg, rgba(17, 24, 34, 0.88), rgba(24, 32, 45, 0.84))',
    border: '1px solid rgba(214, 190, 152, 0.16)',
  },
  themeToggleButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    minHeight: '34px',
    padding: '0 10px',
    borderRadius: '10px',
    color: colors.textSecondary,
    border: '1px solid transparent',
    backgroundColor: 'transparent',
    transitionProperty: 'background-color, border-color, color, transform',
    transitionDuration: motion.fast,
    ':hover': {
      color: colors.textPrimary,
      backgroundColor: 'rgba(255, 255, 255, 0.04)',
    },
  },
  themeToggleButtonActive: {
    color: colors.textPrimary,
    borderColor: 'rgba(214, 190, 152, 0.28)',
    background: 'linear-gradient(120deg, rgba(139, 64, 58, 0.24), rgba(184, 160, 111, 0.18))',
    boxShadow: '0 10px 18px rgba(2, 3, 5, 0.24)',
  },
  themeToggleIcon: {
    width: '14px',
    height: '14px',
  },
  themeToggleLabel: {
    display: {
      default: 'none',
      '@media (min-width: 960px)': 'inline',
    },
    fontSize: '0.72rem',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  desktopNav: {
    display: {
      default: 'none',
      '@media (min-width: 768px)': 'block',
    },
    marginTop: spacing.md,
  },
  navShell: {
    padding: spacing.sm,
    borderRadius: radius.xxl,
    background: `linear-gradient(160deg, ${colors.bgPanel}, ${colors.bgPanelAlt})`,
    border: `1px solid ${colors.borderSubtle}`,
    boxShadow: 'inset 0 1px 0 rgba(245, 237, 222, 0.04), 0 12px 24px rgba(2, 3, 5, 0.32)',
  },
  navShellEnhanced: {
    display: 'grid',
    gap: spacing.lg,
    padding: {
      default: spacing.md,
      '@media (min-width: 1024px)': spacing.lg,
    },
  },
  navHeadRow: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'minmax(0, 1fr)',
      '@media (min-width: 1120px)': 'minmax(0, 1fr) auto',
    },
    gap: spacing.md,
    alignItems: 'stretch',
  },
  coreRailShell: {
    display: 'grid',
    gap: spacing.md,
    minWidth: 0,
  },
  desktopMenuWrap: {
    display: 'grid',
    gap: spacing.sm,
    justifyItems: 'stretch',
    minWidth: {
      default: 'auto',
      '@media (min-width: 1120px)': '236px',
    },
  },
  navMetaBand: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  navSectionMeta: {
    display: 'grid',
    gap: '4px',
    paddingInline: '4px',
    minWidth: 0,
  },
  navCurrentChip: {
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: '32px',
    maxWidth: '100%',
    padding: '0 12px',
    borderRadius: radius.pill,
    border: `1px solid ${colors.accentMuted}`,
    background: `linear-gradient(135deg, ${colors.accentSoft}, rgba(11, 12, 26, 0.24))`,
    color: colors.paperStrong,
    fontSize: typography.secondarySize,
    fontWeight: 600,
    whiteSpace: 'nowrap',
  },
  navSectionMetaCompact: {
    justifyItems: 'end',
    textAlign: 'right',
  },
  navSectionKicker: {
    fontSize: '0.68rem',
    lineHeight: 1,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: colors.paperMuted,
    fontWeight: 700,
  },
  navSectionHint: {
    fontSize: '0.78rem',
    color: colors.paperStrong,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  desktopMenuButton: {
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    alignItems: 'center',
    justifyContent: 'start',
    gap: spacing.md,
    minHeight: '78px',
    minWidth: '188px',
    padding: '14px 16px',
    borderRadius: radius.md,
    border: `1px solid ${colors.lineMuted}`,
    background:
      `radial-gradient(circle at 100% 0%, ${colors.accentMuted}, transparent 36%), linear-gradient(140deg, ${colors.surfaceRaised}, ${colors.surfaceSoft})`,
    color: colors.paper,
    cursor: 'pointer',
    transitionProperty: 'transform, border-color, box-shadow, background-color',
    transitionDuration: motion.base,
    ':hover': {
      transform: 'translateY(-1px)',
      borderColor: 'rgba(220, 197, 160, 0.56)',
      boxShadow: '0 10px 20px rgba(2, 3, 5, 0.34)',
    },
    ':focus-visible': {
      outline: '2px solid rgba(228, 206, 172, 0.76)',
      outlineOffset: '2px',
    },
  },
  desktopMenuButtonActive: {
    borderColor: 'rgba(227, 204, 167, 0.62)',
    boxShadow: '0 10px 20px rgba(2, 3, 5, 0.4)',
    background: 'linear-gradient(140deg, rgba(139, 64, 58, 0.22), rgba(184, 160, 111, 0.18))',
  },
  desktopMenuGlyph: {
    display: 'inline-grid',
    placeItems: 'center',
    width: '44px',
    height: '44px',
    borderRadius: radius.md,
    border: `1px solid ${colors.accentMuted}`,
    backgroundColor: 'rgba(14, 16, 21, 0.88)',
    color: colors.accentStrong,
  },
  desktopMenuCopy: {
    display: 'grid',
    gap: '4px',
    justifyItems: 'start',
    minWidth: 0,
  },
  desktopMenuLabel: {
    fontSize: '0.78rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: 'rgba(226, 214, 191, 0.92)',
    fontWeight: 600,
  },
  desktopMenuHint: {
    fontSize: typography.microSize,
    lineHeight: 1.35,
    color: colors.paperMuted,
    maxWidth: '18ch',
  },
  desktopMenuValue: {
    fontSize: typography.titleSize,
    lineHeight: 1,
    color: colors.paperBright,
    fontFamily: typography.display,
    fontWeight: 700,
  },
  immersivePanel: {
    borderRadius: '20px',
    border: '1px solid rgba(196, 173, 136, 0.24)',
    background:
      'radial-gradient(circle at 12% 8%, rgba(169, 71, 63, 0.18), transparent 32%), radial-gradient(circle at 88% 10%, rgba(130, 185, 173, 0.18), transparent 30%), linear-gradient(165deg, rgba(14, 16, 21, 0.95), rgba(18, 22, 28, 0.95))',
    padding: '14px',
    boxShadow: '0 14px 28px rgba(2, 3, 5, 0.36)',
  },
  immersivePanelHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
    marginBottom: '12px',
    paddingInline: '4px',
  },
  immersivePanelTitle: {
    fontSize: '0.78rem',
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: 'rgba(226, 214, 191, 0.96)',
    fontWeight: 700,
  },
  immersivePanelHint: {
    fontSize: '0.73rem',
    color: 'rgba(194, 182, 160, 0.86)',
  },
  coreRail: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(3, minmax(0, 1fr))',
      '@media (min-width: 1024px)': 'repeat(5, minmax(0, 1fr))',
    },
    gap: spacing.md,
  },
  coreRailCompact: {
    gap: spacing.sm,
  },
  navLinkBase: {
    position: 'relative',
    display: 'block',
    overflow: 'hidden',
    borderRadius: radius.md,
    border: `1px solid ${colors.lineMuted}`,
    color: 'rgba(215, 229, 239, 0.92)',
    textDecoration: 'none',
    transitionProperty: 'transform, border-color, background-color, box-shadow, color',
    transitionDuration: motion.base,
    ':focus-visible': {
      outline: `2px solid ${colors.focusRing}`,
      outlineOffset: '2px',
    },
  },
  coreRailLink: {
    minHeight: '78px',
    background:
      `radial-gradient(circle at 100% 0%, ${colors.accentMuted}, transparent 32%), linear-gradient(160deg, ${colors.surfaceRaised}, ${colors.surfaceBase})`,
    boxShadow: `0 12px 24px ${colors.shadowSoft}`,
  },
  coreRailLinkCompact: {
    minHeight: '72px',
  },
  navLinkInactive: {
    backgroundColor: colors.surfaceSoft,
    ':hover': {
      backgroundColor: colors.surfaceRaised,
      borderColor: colors.lineStrong,
      color: 'rgba(245, 236, 220, 0.98)',
      transform: 'translateY(-2px)',
      boxShadow: `0 16px 28px ${colors.shadowSoft}`,
    },
  },
  navLinkContent: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  coreLinkContent: {
    minHeight: '100%',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexDirection: 'column',
    padding: '14px',
  },
  coreLinkMeta: {
    display: 'flex',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  coreLinkIndex: {
    fontSize: typography.microSize,
    lineHeight: 1,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    color: colors.paperMuted,
    fontWeight: 700,
  },
  commandDeck: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 900px)': 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 1200px)': 'repeat(3, minmax(0, 1fr))',
    },
    gap: spacing.md,
  },
  commandGroup: {
    display: 'grid',
    gap: spacing.md,
    padding: spacing.lg,
    borderRadius: '20px',
    background: `linear-gradient(160deg, ${colors.surfaceRaised}, ${colors.surfaceBase})`,
    border: `1px solid ${colors.lineMuted}`,
    boxShadow: `inset 0 1px 0 rgba(245, 237, 222, 0.04), 0 10px 18px ${colors.shadowSoft}`,
  },
  groupLabel: {
    fontSize: '0.72rem',
    lineHeight: 1,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: 'rgba(213, 194, 160, 0.74)',
    paddingLeft: '4px',
  },
  groupItems: {
    display: 'grid',
    gap: '8px',
  },
  commandLinkContent: {
    minHeight: '52px',
    padding: '0 14px',
  },
  navActiveIndicator: {
    position: 'absolute',
    inset: 0,
    borderRadius: 'inherit',
    background:
      'radial-gradient(circle at 0% 0%, rgba(169, 208, 226, 0.16), transparent 34%), linear-gradient(135deg, rgba(139, 64, 58, 0.28), rgba(184, 160, 111, 0.24))',
    border: '1px solid rgba(218, 195, 160, 0.34)',
    boxShadow: '0 14px 24px rgba(2, 3, 5, 0.34), inset 0 1px 0 rgba(245, 237, 222, 0.12)',
  },
  orderDot: {
    width: '30px',
    height: '30px',
    flex: '0 0 auto',
    display: 'inline-grid',
    placeItems: 'center',
    borderRadius: radius.pill,
    border: `1px solid ${colors.accentMuted}`,
    backgroundColor: 'rgba(32, 30, 34, 0.9)',
    color: colors.accentStrong,
    boxShadow: `inset 0 0 12px ${colors.accentGlow}`,
  },
  accentIcon: {
    color: colors.accentStrong,
  },
  orderLabel: {
    fontSize: '0.84rem',
    lineHeight: 1.2,
    fontWeight: 600,
    textAlign: 'center',
    whiteSpace: 'normal',
    textWrap: 'balance',
  },
  coreOrderLabel: {
    textAlign: 'left',
  },
  layoutRoot: {
    position: 'relative',
    zIndex: 30,
    overflowX: 'clip',
  },
  translateTransition: {
    transitionProperty: 'transform',
    transitionDuration: motion.slow,
  },
  hideTop: {
    transform: 'translateY(-100%)',
  },
  hideBottom: {
    transform: 'translateY(100%)',
  },
  main: {
    minHeight: '100vh',
    paddingBottom: {
      default: 'calc(96px + env(safe-area-inset-bottom))',
      '@media (min-width: 768px)': 0,
    },
  },
  mainShifted: {
    marginTop: 'calc(var(--header-height, 80px) * -1)',
  },
  mainInner: {
    width: '100%',
    maxWidth: layout.container,
    marginInline: 'auto',
    overflowX: 'clip',
    paddingInline: {
      default: spacing.md,
      '@media (min-width: 640px)': spacing.xl,
      '@media (min-width: 1024px)': spacing.xxxl,
    },
    paddingTop: {
      default: '16px',
      '@media (min-width: 640px)': '24px',
    },
  },
  pageShell: {
    position: 'relative',
    borderRadius: radius.xl,
    overflow: 'hidden',
    isolation: 'isolate',
    border: `1px solid ${colors.borderSubtle}`,
    background: `linear-gradient(160deg, ${colors.bgPanel}, ${colors.panelBottom})`,
    boxShadow: '0 12px 24px rgba(2, 3, 5, 0.3)',
    transformOrigin: 'top center',
    willChange: 'opacity, transform',
    '::before': {
      content: "''",
      position: 'absolute',
      inset: '12px 6%',
      borderRadius: radius.pill,
      background:
        'radial-gradient(circle at 86% 24%, rgba(169, 208, 226, 0.14), transparent 16%), radial-gradient(circle, rgba(116, 167, 217, 0.16), transparent 68%)',
      filter: 'blur(16px)',
      opacity: 0,
      animationName: 'sectionMist',
      animationDuration: '0.7s',
      animationTimingFunction: 'ease',
      animationFillMode: 'forwards',
      pointerEvents: 'none',
      zIndex: 0,
    },
    '::after': {
      content: "''",
      position: 'absolute',
      top: '10%',
      left: '50%',
      width: '120px',
      height: '120px',
      borderRadius: radius.pill,
      border: '1px solid rgba(143, 185, 204, 0.35)',
      background: 'radial-gradient(circle, rgba(143, 185, 204, 0.2), transparent 70%)',
      boxShadow: 'inset 0 0 20px rgba(143, 185, 204, 0.2)',
      opacity: 0,
      transform: 'translate(-50%, -50%)',
      animationName: 'sealBloom',
      animationDuration: '0.8s',
      animationTimingFunction: 'ease',
      animationFillMode: 'forwards',
      pointerEvents: 'none',
      zIndex: 0,
    },
  },
  pageShellContent: {
    position: 'relative',
    zIndex: 1,
  },
  pageShellAbout: {
    '::before': {
      background:
        'radial-gradient(circle at 84% 22%, rgba(143, 185, 204, 0.18), transparent 18%), radial-gradient(circle, rgba(143, 185, 204, 0.14), transparent 68%)',
    },
    '::after': {
      borderColor: 'rgba(143, 185, 204, 0.35)',
    },
  },
  pageShellRegistration: {
    '::before': {
      background:
        'radial-gradient(circle at 86% 24%, rgba(143, 185, 204, 0.12) 0 10%, transparent 14%), radial-gradient(circle at 86% 24%, rgba(143, 185, 204, 0.1) 0 20%, transparent 24%), radial-gradient(circle, rgba(143, 185, 204, 0.18), transparent 70%)',
    },
    '::after': {
      borderColor: 'rgba(143, 185, 204, 0.45)',
    },
  },
  pageShellSchedule: {
    '::before': {
      background:
        'radial-gradient(circle at 86% 24%, rgba(127, 163, 138, 0.18), transparent 20%), radial-gradient(circle, rgba(127, 163, 138, 0.2), transparent 70%)',
      animationDuration: '0.9s',
    },
    '::after': {
      borderColor: 'rgba(127, 163, 138, 0.5)',
      transform: 'translate(calc(-50% - 16px), -50%) rotate(-6deg)',
      animationDuration: '1s',
    },
  },
  pageShellCalendar: {
    '::before': {
      background:
        'radial-gradient(circle at 82% 24%, rgba(127, 163, 138, 0.14), transparent 22%), radial-gradient(circle, rgba(127, 163, 138, 0.16), transparent 70%)',
    },
    '::after': {
      borderColor: 'rgba(127, 163, 138, 0.42)',
    },
  },
  pageShellAnalytics: {
    '::before': {
      background:
        'radial-gradient(circle at 82% 20%, rgba(116, 167, 217, 0.16), transparent 18%), radial-gradient(circle, rgba(116, 167, 217, 0.18), transparent 70%)',
    },
    '::after': {
      borderColor: 'rgba(116, 167, 217, 0.45)',
    },
  },
  pageShellWorkflow: {
    '::before': {
      background:
        'radial-gradient(circle at 82% 24%, rgba(201, 168, 106, 0.16), transparent 18%), radial-gradient(circle, rgba(201, 168, 106, 0.16), transparent 70%)',
    },
    '::after': {
      borderColor: 'rgba(201, 168, 106, 0.42)',
      transform: 'translate(calc(-50% - 8px), -50%) rotate(6deg)',
    },
  },
  pageShellIntegrations: {
    '::before': {
      background:
        'radial-gradient(circle at 82% 20%, rgba(124, 163, 142, 0.18), transparent 18%), radial-gradient(circle, rgba(116, 167, 217, 0.12), transparent 70%)',
    },
    '::after': {
      borderColor: 'rgba(124, 163, 142, 0.42)',
    },
  },
  pageShellPvp: {
    '::before': {
      background:
        'radial-gradient(circle at 84% 20%, rgba(139, 64, 58, 0.18), transparent 18%), radial-gradient(circle, rgba(139, 64, 58, 0.18), transparent 70%)',
    },
    '::after': {
      borderColor: 'rgba(208, 122, 114, 0.42)',
      transform: 'translate(calc(-50% + 10px), -50%) rotate(-8deg)',
    },
  },
  pageShellGuides: {
    '::before': {
      background:
        'radial-gradient(circle at 84% 20%, rgba(74, 144, 176, 0.18), transparent 18%), radial-gradient(circle, rgba(74, 144, 176, 0.22), transparent 70%)',
      animationDuration: '0.8s',
    },
    '::after': {
      borderColor: 'rgba(74, 144, 176, 0.55)',
      transform: 'translate(calc(-50% - 10px), calc(-50% + 6px)) rotate(10deg)',
      animationDuration: '1.05s',
    },
  },
  pageShellHelp: {
    '::before': {
      background:
        'radial-gradient(circle at 84% 24%, rgba(35, 80, 107, 0.22), transparent 20%), radial-gradient(circle, rgba(35, 80, 107, 0.22), transparent 70%)',
      animationDuration: '0.75s',
    },
    '::after': {
      borderColor: 'rgba(35, 80, 107, 0.5)',
      transform: 'translate(calc(-50% + 18px), -50%) rotate(8deg)',
      animationDuration: '0.95s',
    },
  },
  pageShellAbsences: {
    '::before': {
      background:
        'radial-gradient(circle at 84% 22%, rgba(143, 185, 204, 0.16), transparent 18%), radial-gradient(circle, rgba(143, 185, 204, 0.14), transparent 70%)',
      animationDuration: '1s',
    },
    '::after': {
      borderColor: 'rgba(143, 185, 204, 0.35)',
      boxShadow: 'inset 0 0 20px rgba(143, 185, 204, 0.15)',
      transform: 'translate(calc(-50% + 8px), calc(-50% + 10px)) rotate(-4deg)',
      animationDuration: '1.2s',
    },
  },
  pageShellNews: {
    '::before': {
      background:
        'radial-gradient(circle at 84% 24%, rgba(143, 185, 204, 0.18), transparent 18%), radial-gradient(circle, rgba(143, 185, 204, 0.14), transparent 68%)',
      animationDuration: '0.65s',
    },
    '::after': {
      borderStyle: 'dashed',
      transform: 'translate(-50%, calc(-50% - 10px)) rotate(-12deg)',
      animationDuration: '0.8s',
    },
  },
  pageShellCalculator: {
    '::before': {
      background:
        'radial-gradient(circle at 84% 24%, rgba(127, 163, 138, 0.16), transparent 18%), radial-gradient(circle, rgba(127, 163, 138, 0.18), transparent 68%)',
      animationDuration: '0.7s',
    },
    '::after': {
      borderColor: 'rgba(127, 163, 138, 0.45)',
      transform: 'translate(calc(-50% - 14px), -50%) rotate(6deg)',
      animationDuration: '0.9s',
    },
  },
  pageShellProfile: {
    '::before': {
      background:
        'radial-gradient(circle at 84% 24%, rgba(201, 168, 106, 0.16), transparent 18%), radial-gradient(circle, rgba(201, 168, 106, 0.14), transparent 68%)',
    },
    '::after': {
      borderColor: 'rgba(201, 168, 106, 0.42)',
    },
  },
  mobileNavRoot: {
    display: {
      default: 'block',
      '@media (min-width: 768px)': 'none',
    },
    position: 'fixed',
    insetInline: 0,
    bottom: 0,
    zIndex: 40,
    paddingLeft: 'max(12px, env(safe-area-inset-left))',
    paddingRight: 'max(12px, env(safe-area-inset-right))',
    paddingBottom: 'max(10px, env(safe-area-inset-bottom))',
    pointerEvents: 'none',
  },
  mobileSheetScrim: {
    position: 'fixed',
    inset: 0,
    border: 'none',
    width: '100%',
    height: '100%',
    padding: 0,
    margin: 0,
    background: 'linear-gradient(180deg, rgba(8, 10, 14, 0.3), rgba(8, 10, 14, 0.62))',
    backdropFilter: 'blur(2px)',
    zIndex: 54,
    cursor: 'pointer',
    touchAction: 'none',
  },
  mobileSheetFrame: {
    position: 'fixed',
    inset: 'calc(var(--safe-top) + 10px) 10px calc(88px + env(safe-area-inset-bottom)) 10px',
    zIndex: 55,
    border: '1px solid rgba(192, 167, 121, 0.3)',
    borderRadius: '26px',
    background:
      'radial-gradient(circle at 12% 8%, rgba(169, 71, 63, 0.2), transparent 36%), radial-gradient(circle at 88% 10%, rgba(130, 185, 173, 0.18), transparent 32%), linear-gradient(180deg, rgba(16, 18, 23, 0.98), rgba(12, 14, 19, 0.96))',
    boxShadow: '0 18px 34px rgba(2, 3, 5, 0.52)',
    backdropFilter: 'blur(12px)',
    overflow: 'hidden',
    pointerEvents: 'auto',
    '::before': {
      content: "''",
      position: 'absolute',
      inset: 0,
      borderRadius: '24px',
      border: '1px solid rgba(240, 224, 196, 0.08)',
      pointerEvents: 'none',
    },
  },
  mobileSheetStack: {
    display: 'grid',
    gridTemplateRows: 'auto auto minmax(0, 1fr)',
    gap: spacing.sm,
    height: '100%',
    padding: '12px',
  },
  mobileSheetHeader: {
    display: 'grid',
    gap: spacing.xs,
    paddingInline: '4px',
  },
  mobileSheetHeaderRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  mobileSheetHeaderCopy: {
    display: 'grid',
    gap: spacing.xs,
    minWidth: 0,
  },
  mobileSheetTitle: {
    fontSize: '0.76rem',
    lineHeight: 1,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: colors.paperMuted,
    fontWeight: 700,
  },
  mobileSheetHint: {
    fontSize: '0.78rem',
    color: colors.paperStrong,
    lineHeight: 1.4,
    maxWidth: '28ch',
  },
  mobileSheetClose: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: '0 0 auto',
    minWidth: '40px',
    minHeight: '40px',
    borderRadius: radius.md,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgField,
    color: colors.paperStrong,
    boxShadow: colors.shadowInset,
    transitionProperty: 'transform, border-color, background-color, box-shadow',
    transitionDuration: motion.fast,
    transitionTimingFunction: motion.easeStandard,
    ':hover': {
      borderColor: colors.borderStrong,
      backgroundColor: colors.bgHover,
      transform: 'translateY(-1px)',
      boxShadow: `0 10px 20px ${colors.shadowSoft}`,
    },
    ':focus-visible': {
      outline: `2px solid ${colors.focusRing}`,
      outlineOffset: '2px',
    },
  },
  mobileSheetStatusRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  mobileSheetStatusChip: {
    display: 'inline-grid',
    gap: spacing.xxs,
    minHeight: '36px',
    alignContent: 'center',
    padding: '6px 10px',
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderDefault}`,
    background: `linear-gradient(145deg, ${colors.surfaceRaised}, ${colors.surfaceBase})`,
    boxShadow: colors.shadowInset,
  },
  mobileSheetStatusChipActive: {
    borderColor: colors.accentEdge,
    background: `linear-gradient(135deg, ${colors.accentSoft}, ${colors.surfaceBase})`,
  },
  mobileSheetStatusKicker: {
    fontSize: typography.microSize,
    lineHeight: 1,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: colors.paperMuted,
    fontWeight: 700,
  },
  mobileSheetStatusValue: {
    fontSize: typography.microSize,
    lineHeight: 1.1,
    color: colors.paperBright,
    fontWeight: 600,
  },
  mobileSheetScroll: {
    display: 'grid',
    gap: spacing.sm,
    minHeight: 0,
    overflowY: 'auto',
    overscrollBehavior: 'contain',
    paddingBottom: spacing.xxs,
    paddingRight: '2px',
  },
  mobileGroup: {
    display: 'grid',
    gap: spacing.sm,
    padding: '10px',
    borderRadius: radius.xl,
    border: `1px solid ${colors.lineMuted}`,
    background: `linear-gradient(160deg, ${colors.surfaceRaised}, ${colors.surfaceBase})`,
    boxShadow: colors.shadowInset,
  },
  mobileGroupMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  mobileGroupCount: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '26px',
    minHeight: '26px',
    paddingInline: spacing.sm,
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgPanel,
    color: colors.paperStrong,
    fontSize: typography.microSize,
    fontWeight: 700,
  },
  mobileSheetGrid: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 640px)': 'repeat(3, minmax(0, 1fr))',
    },
    gap: spacing.xs,
  },
  mobileSheetLink: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    minWidth: 0,
    minHeight: '56px',
    padding: '10px',
    borderRadius: radius.md,
    border: '1px solid rgba(146, 126, 92, 0.42)',
    backgroundColor: 'rgba(22, 24, 30, 0.76)',
    color: 'rgba(222, 235, 244, 0.96)',
    textDecoration: 'none',
    boxShadow: 'inset 0 1px 0 rgba(214, 236, 247, 0.05)',
    transitionProperty: 'transform, border-color, background-color, box-shadow',
    transitionDuration: motion.base,
    transitionTimingFunction: motion.easeStandard,
    ':hover': {
      backgroundColor: 'rgba(41, 33, 36, 0.94)',
      borderColor: 'rgba(214, 190, 152, 0.52)',
      transform: 'translateY(-1px)',
    },
    ':active': {
      transform: 'translateY(1px) scale(0.99)',
    },
    ':focus-visible': {
      outline: '2px solid rgba(196, 227, 241, 0.72)',
      outlineOffset: '2px',
    },
  },
  mobileSheetLinkActive: {
    borderColor: 'rgba(227, 203, 166, 0.58)',
    background: 'linear-gradient(125deg, rgba(139, 64, 58, 0.24), rgba(184, 160, 111, 0.18))',
    boxShadow: '0 10px 20px rgba(2, 3, 5, 0.4)',
  },
  mobileSheetIcon: {
    display: 'inline-grid',
    placeItems: 'center',
    width: '36px',
    height: '36px',
    borderRadius: '12px',
    border: '1px solid rgba(192, 167, 121, 0.22)',
    backgroundColor: 'rgba(20, 18, 24, 0.86)',
    color: colors.accentStrong,
    flex: '0 0 auto',
  },
  mobileSheetIconActive: {
    borderColor: colors.accentEdgeStrong,
    background: `linear-gradient(135deg, ${colors.accentSoft}, ${colors.bgField})`,
    color: colors.paperBright,
  },
  mobileSheetText: {
    display: 'grid',
    gap: '2px',
    minWidth: 0,
  },
  mobileSheetLabel: {
    fontSize: typography.microSize,
    lineHeight: 1.3,
    color: colors.paperStrong,
    fontWeight: 600,
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
    textWrap: 'balance',
  },
  mobileSheetLabelActive: {
    color: colors.paperBright,
  },
  mobileSheetCurrentTag: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 'fit-content',
    minHeight: '20px',
    padding: '0 8px',
    borderRadius: radius.pill,
    border: `1px solid ${colors.accentEdge}`,
    background: `linear-gradient(135deg, ${colors.accentSoft}, ${colors.accentMuted})`,
    color: colors.paperBright,
    fontSize: typography.microSize,
    lineHeight: 1,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    fontWeight: 700,
  },
  mobileDock: {
    position: 'relative',
    width: 'min(100%, 560px)',
    marginInline: 'auto',
    padding: spacing.sm,
    borderRadius: radius.xxl,
    boxShadow: '0 -12px 24px rgba(2, 3, 5, 0.5)',
    overflow: 'hidden',
    background:
      `radial-gradient(circle at 16% 0%, ${colors.accentMuted}, transparent 38%), radial-gradient(circle at 84% 0%, ${colors.infoSurface}, transparent 34%), linear-gradient(180deg, ${colors.bgPanel}, ${colors.bgPanelAlt})`,
    border: `1px solid ${colors.borderDefault}`,
    backdropFilter: 'blur(12px)',
    pointerEvents: 'auto',
    '::before': {
      content: "''",
      position: 'absolute',
      inset: 0,
      borderRadius: '24px',
      border: '1px solid rgba(238, 223, 194, 0.06)',
      pointerEvents: 'none',
    },
  },
  mobileDockMeta: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'start',
    gap: spacing.sm,
    padding: '6px 8px 10px',
  },
  mobileDockCopy: {
    display: 'grid',
    gap: spacing.xs,
    minWidth: 0,
  },
  mobileDockKicker: {
    fontSize: '0.65rem',
    lineHeight: 1,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: colors.paperMuted,
    fontWeight: 700,
  },
  mobileDockHint: {
    fontSize: '0.78rem',
    color: colors.paperStrong,
    lineHeight: 1.35,
    maxWidth: '24ch',
  },
  mobileDockStatus: {
    display: 'inline-grid',
    gap: spacing.xxs,
    minHeight: '40px',
    alignContent: 'center',
    justifyItems: 'end',
    padding: '6px 10px',
    borderRadius: radius.lg,
    border: `1px solid ${colors.borderDefault}`,
    background: `linear-gradient(145deg, ${colors.surfaceRaised}, ${colors.surfaceBase})`,
    boxShadow: colors.shadowInset,
    maxWidth: '44%',
  },
  mobileDockStatusKicker: {
    fontSize: typography.microSize,
    lineHeight: 1,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: colors.paperMuted,
    fontWeight: 700,
  },
  mobileDockStatusValue: {
    fontSize: typography.secondarySize,
    lineHeight: typography.secondaryLine,
    color: colors.paperBright,
    fontWeight: 600,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  mobileDockInner: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, minmax(0, 1fr))',
    gap: spacing.xs,
  },
  mobileChip: {
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    minWidth: 0,
    minHeight: '70px',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.lg,
    padding: '10px 5px 8px',
    backdropFilter: 'blur(10px)',
    backgroundColor: colors.surfaceSoft,
    border: `1px solid ${colors.lineMuted}`,
    color: colors.paper,
    textDecoration: 'none',
    boxShadow: 'inset 0 1px 0 rgba(214, 236, 247, 0.05)',
    transitionProperty: 'transform, background-color, border-color',
    transitionDuration: motion.slow,
    transitionTimingFunction: motion.easeStandard,
    touchAction: 'manipulation',
    ':hover': {
      backgroundColor: colors.surfaceRaised,
      borderColor: colors.lineStrong,
      transform: 'translateY(-1px)',
    },
    ':active': {
      transform: 'translateY(1px) scale(0.985)',
      backgroundColor: 'rgba(47, 37, 40, 0.95)',
    },
    ':focus-visible': {
      outline: '2px solid rgba(196, 227, 241, 0.78)',
      outlineOffset: '2px',
    },
  },
  mobileChipActive: {
    background: 'linear-gradient(125deg, rgba(139, 64, 58, 0.24), rgba(184, 160, 111, 0.2))',
    borderColor: 'rgba(227, 203, 166, 0.56)',
    boxShadow: '0 10px 20px rgba(2, 3, 5, 0.46)',
    '::after': {
      content: "''",
      position: 'absolute',
      inset: 0,
      border: '1px solid rgba(218, 195, 160, 0.4)',
      borderRadius: '20px',
      animationName: {
        default: 'navPulse',
      },
      animationDuration: '2.2s',
      animationTimingFunction: 'ease-in-out',
      animationIterationCount: 'infinite',
      pointerEvents: 'none',
    },
  },
  mobileMore: {
    minWidth: 0,
  },
  mobileChipBadge: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '22px',
    minHeight: '22px',
    paddingInline: '6px',
    borderRadius: radius.pill,
    border: `1px solid ${colors.borderDefault}`,
    backgroundColor: colors.bgField,
    color: colors.paperStrong,
    fontSize: typography.microSize,
    lineHeight: 1,
    fontWeight: 700,
    zIndex: 1,
  },
  mobileLinkContent: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
    width: '100%',
  },
  mobileDockIcon: {
    display: 'inline-grid',
    placeItems: 'center',
    width: '32px',
    height: '32px',
    borderRadius: radius.md,
    border: `1px solid ${colors.accentMuted}`,
    backgroundColor: colors.bgField,
    color: colors.accentStrong,
    boxShadow: colors.shadowInset,
  },
  mobileDockIconActive: {
    borderColor: colors.accentEdgeStrong,
    background: `linear-gradient(135deg, ${colors.accentSoft}, ${colors.bgField})`,
    color: colors.paperBright,
  },
  mobileLabel: {
    fontSize: {
      default: '10px',
      '@media (min-width: 480px)': typography.microSize,
      '@media (min-width: 640px)': '11px',
    },
    fontWeight: 600,
    lineHeight: 1.15,
    letterSpacing: '0.01em',
    whiteSpace: 'normal',
    textAlign: 'center',
    textWrap: 'balance',
    overflowWrap: 'anywhere',
    wordBreak: 'break-word',
  },
  mobileLabelActive: {
    color: colors.paperBright,
  },
});
