import * as stylex from '@stylexjs/stylex';
import { colors, radius, typography } from '../../lib/stylex/tokens.stylex';

export const shellStyles = stylex.create({
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 40,
    overflow: 'visible',
    background:
      'radial-gradient(circle at 8% 10%, rgba(110, 190, 230, 0.18), transparent 36%), linear-gradient(105deg, rgba(6, 13, 20, 0.96), rgba(9, 16, 24, 0.95), rgba(6, 13, 20, 0.96))',
    borderBottom: '1px solid rgba(72, 110, 132, 0.52)',
    boxShadow: '0 18px 44px rgba(4, 8, 12, 0.72)',
    backdropFilter: 'blur(18px)',
    paddingTop: 'var(--safe-top)',
    paddingLeft: 'var(--safe-left)',
    paddingRight: 'var(--safe-right)',
  },
  headerCompact: {
    boxShadow: '0 14px 34px rgba(4, 8, 12, 0.6)',
  },
  headerPanel: {
    position: 'relative',
    width: '100%',
    maxWidth: '80rem',
    marginInline: 'auto',
    paddingInline: {
      default: '16px',
      '@media (min-width: 640px)': '24px',
    },
    paddingTop: {
      default: '12px',
      '@media (min-width: 640px)': '14px',
    },
    paddingBottom: {
      default: '12px',
      '@media (min-width: 640px)': '14px',
    },
    '::after': {
      content: "''",
      position: 'absolute',
      inset: 0,
      borderRadius: radius.xl,
      border: '1px solid rgba(143, 185, 204, 0.12)',
      pointerEvents: 'none',
    },
  },
  headerPanelCompact: {
    paddingTop: '10px',
    paddingBottom: '10px',
  },
  headerTop: {
    display: 'flex',
    flexDirection: {
      default: 'column',
      '@media (min-width: 1024px)': 'row',
    },
    alignItems: {
      default: 'stretch',
      '@media (min-width: 1024px)': 'flex-start',
    },
    justifyContent: {
      default: 'flex-start',
      '@media (min-width: 1024px)': 'space-between',
    },
    gap: '16px',
  },
  brandBlock: {
    display: 'flex',
    minWidth: 0,
    alignItems: {
      default: 'flex-start',
      '@media (min-width: 640px)': 'center',
    },
    gap: {
      default: '12px',
      '@media (min-width: 640px)': '16px',
    },
    textAlign: 'left',
    paddingRight: '12px',
    color: 'inherit',
    textDecoration: 'none',
  },
  brandSealWrap: {
    position: 'relative',
    flexShrink: 0,
  },
  brandStatusDot: {
    position: 'absolute',
    top: '-4px',
    right: '-4px',
    display: {
      default: 'none',
      '@media (min-width: 640px)': 'block',
    },
    width: '16px',
    height: '16px',
    borderRadius: radius.pill,
    backgroundColor: '#5fd1d4',
    border: '2px solid #0a1118',
  },
  compactSeal: {
    transform: 'scale(0.92)',
  },
  brandTextWrap: {
    minWidth: 0,
    textAlign: 'left',
  },
  brandTitle: {
    margin: 0,
    fontSize: {
      default: '1.9rem',
      '@media (min-width: 640px)': '1.5rem',
    },
    fontWeight: 700,
    fontFamily: typography.display,
    lineHeight: 1,
  },
  brandSubtitle: {
    marginTop: '4px',
    fontSize: {
      default: '0.75rem',
      '@media (min-width: 640px)': '0.875rem',
    },
    lineHeight: 1.35,
    whiteSpace: {
      default: 'normal',
      '@media (min-width: 640px)': 'nowrap',
    },
  },
  headerOath: {
    display: {
      default: 'none',
      '@media (min-width: 640px)': 'flex',
    },
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: '8px',
    marginTop: '8px',
  },
  headerOathCompact: {
    display: 'none',
  },
  mobileSectionTag: {
    marginTop: '8px',
    display: {
      default: 'block',
      '@media (min-width: 640px)': 'none',
    },
  },
  toolbar: {
    display: 'flex',
    width: {
      default: '100%',
      '@media (min-width: 640px)': 'auto',
    },
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: {
      default: 'space-between',
      '@media (min-width: 640px)': 'flex-end',
    },
    gap: '8px',
    padding: '8px',
    borderRadius: '20px',
    background: 'linear-gradient(135deg, rgba(8, 15, 23, 0.86), rgba(15, 27, 37, 0.72))',
    border: '1px solid rgba(96, 132, 152, 0.34)',
    boxShadow: 'inset 0 1px 0 rgba(207, 230, 245, 0.04)',
  },
  select: {
    minWidth: '102px',
    flex: {
      default: '1 1 0%',
      '@media (min-width: 640px)': '0 0 auto',
    },
    borderRadius: '12px',
    padding: '10px 16px',
    fontSize: '0.875rem',
    fontWeight: 500,
    minHeight: '42px',
    backgroundColor: 'rgba(11, 22, 31, 0.84)',
    border: '1px solid rgba(77, 112, 134, 0.46)',
    color: colors.paperStrong,
    backdropFilter: 'blur(12px)',
    transitionProperty: 'background-color, border-color, transform, box-shadow',
    transitionDuration: '200ms',
  },
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '10px',
    borderRadius: '12px',
    backgroundColor: 'rgba(11, 22, 31, 0.84)',
    border: '1px solid rgba(77, 112, 134, 0.46)',
    backdropFilter: 'blur(12px)',
    transitionProperty: 'background-color, border-color, transform, box-shadow',
    transitionDuration: '200ms',
    color: 'inherit',
    textDecoration: 'none',
    cursor: 'pointer',
    ':hover': {
      backgroundColor: 'rgba(18, 35, 48, 0.92)',
      borderColor: 'rgba(151, 194, 216, 0.65)',
      transform: 'translateY(-1px)',
      boxShadow: '0 14px 28px rgba(3, 8, 12, 0.46)',
    },
  },
  iconButtonActive: {
    borderColor: 'rgba(207, 230, 245, 0.75)',
    boxShadow: '0 18px 34px rgba(4, 8, 12, 0.62), 0 0 18px rgba(143, 185, 204, 0.25)',
  },
  iconButtonAccent: {
    background: 'linear-gradient(130deg, rgba(38, 108, 142, 0.9), rgba(119, 167, 194, 0.65))',
    border: '1px solid rgba(163, 202, 222, 0.58)',
    boxShadow: '0 16px 30px rgba(4, 8, 12, 0.55), 0 0 18px rgba(143, 185, 204, 0.25)',
    ':hover': {
      background: 'linear-gradient(130deg, rgba(45, 122, 166, 0.9), rgba(176, 212, 230, 0.7))',
      borderColor: 'rgba(207, 230, 245, 0.75)',
    },
  },
  desktopNav: {
    display: {
      default: 'none',
      '@media (min-width: 768px)': 'block',
    },
    marginTop: '12px',
  },
  navShell: {
    padding: '10px',
    borderRadius: '22px',
    background: 'linear-gradient(160deg, rgba(7, 13, 20, 0.92), rgba(12, 22, 31, 0.88))',
    border: '1px solid rgba(94, 130, 150, 0.28)',
    boxShadow: 'inset 0 1px 0 rgba(207, 230, 245, 0.04), 0 18px 38px rgba(4, 8, 12, 0.32)',
  },
  navShellEnhanced: {
    display: 'grid',
    gap: '12px',
    padding: '12px',
  },
  coreRail: {
    display: 'grid',
    gridTemplateColumns: {
      default: 'repeat(3, minmax(0, 1fr))',
      '@media (min-width: 1200px)': 'repeat(6, minmax(0, 1fr))',
    },
    gap: '10px',
  },
  coreRailCompact: {
    gap: '8px',
  },
  navLinkBase: {
    position: 'relative',
    display: 'block',
    overflow: 'hidden',
    borderRadius: radius.md,
    color: 'rgba(215, 229, 239, 0.92)',
    textDecoration: 'none',
  },
  navLinkInactive: {
    backgroundColor: 'rgba(10, 19, 28, 0.72)',
    border: '1px solid rgba(77, 112, 134, 0.22)',
    ':hover': {
      backgroundColor: 'rgba(17, 31, 43, 0.92)',
      borderColor: 'rgba(143, 185, 204, 0.4)',
      color: 'rgba(232, 240, 245, 0.98)',
    },
  },
  navLinkContent: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  coreLinkContent: {
    minHeight: '58px',
    justifyContent: 'center',
    padding: '0 14px',
  },
  commandDeck: {
    display: 'grid',
    gridTemplateColumns: {
      default: '1fr',
      '@media (min-width: 900px)': 'repeat(2, minmax(0, 1fr))',
      '@media (min-width: 1200px)': 'repeat(3, minmax(0, 1fr))',
    },
    gap: '12px',
  },
  commandGroup: {
    display: 'grid',
    gap: '10px',
    padding: '12px',
    borderRadius: '18px',
    background: 'linear-gradient(160deg, rgba(9, 16, 24, 0.86), rgba(12, 20, 30, 0.8))',
    border: '1px solid rgba(90, 125, 145, 0.22)',
    boxShadow: 'inset 0 1px 0 rgba(214, 232, 241, 0.04)',
  },
  groupLabel: {
    fontSize: '0.72rem',
    lineHeight: 1,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: 'rgba(153, 183, 198, 0.76)',
    paddingLeft: '4px',
  },
  groupItems: {
    display: 'grid',
    gap: '8px',
  },
  commandLinkContent: {
    minHeight: '48px',
    padding: '0 12px',
  },
  navActiveIndicator: {
    position: 'absolute',
    inset: 0,
    borderRadius: 'inherit',
    background: 'linear-gradient(135deg, rgba(29, 60, 81, 0.94), rgba(13, 25, 36, 0.96))',
    border: '1px solid rgba(170, 210, 229, 0.32)',
    boxShadow: '0 14px 30px rgba(4, 8, 12, 0.38), inset 0 1px 0 rgba(218, 234, 243, 0.12)',
  },
  orderDot: {
    width: '22px',
    height: '22px',
    flex: '0 0 auto',
    display: 'inline-grid',
    placeItems: 'center',
    borderRadius: '999px',
    backgroundColor: 'rgba(16, 30, 42, 0.86)',
    color: colors.accentStrong,
  },
  orderLabel: {
    fontSize: '0.88rem',
    lineHeight: 1.2,
    fontWeight: 600,
  },
  layoutRoot: {
    position: 'relative',
    zIndex: 30,
    overflowX: 'clip',
  },
  translateTransition: {
    transitionProperty: 'transform',
    transitionDuration: '300ms',
  },
  hideTop: {
    transform: 'translateY(-100%)',
  },
  hideBottom: {
    transform: 'translateY(100%)',
  },
  main: {
    minHeight: '100vh',
    paddingBottom: {
      default: 'calc(96px + env(safe-area-inset-bottom))',
      '@media (min-width: 768px)': 0,
    },
  },
  mainShifted: {
    marginTop: 'calc(var(--header-height, 80px) * -1)',
  },
  mainInner: {
    width: '100%',
    maxWidth: '1280px',
    marginInline: 'auto',
    overflowX: 'clip',
    paddingInline: {
      default: '12px',
      '@media (min-width: 640px)': '20px',
      '@media (min-width: 1024px)': '32px',
    },
    paddingTop: {
      default: '16px',
      '@media (min-width: 640px)': '24px',
    },
  },
  pageShell: {
    borderRadius: '16px',
    overflow: 'hidden',
  },
  mobileNavRoot: {
    display: {
      default: 'block',
      '@media (min-width: 768px)': 'none',
    },
    position: 'fixed',
    insetInline: 0,
    bottom: 0,
    zIndex: 40,
    paddingLeft: 'max(12px, env(safe-area-inset-left))',
    paddingRight: 'max(12px, env(safe-area-inset-right))',
    paddingBottom: 'max(10px, env(safe-area-inset-bottom))',
  },
  mobileSheetFrame: {
    position: 'relative',
    marginBottom: '12px',
    border: '1px solid rgba(67, 103, 124, 0.58)',
    borderRadius: '24px',
    background: 'linear-gradient(180deg, rgba(8, 14, 20, 0.97), rgba(11, 18, 26, 0.94))',
    boxShadow: '0 24px 48px rgba(4, 8, 12, 0.65)',
    backdropFilter: 'blur(18px)',
    overflow: 'hidden',
    '::before': {
      content: "''",
      position: 'absolute',
      inset: 0,
      borderRadius: '24px',
      border: '1px solid rgba(207, 230, 245, 0.08)',
      pointerEvents: 'none',
    },
  },
  mobileSheetStack: {
    display: 'grid',
    gap: '12px',
    padding: '12px',
  },
  mobileGroup: {
    display: 'grid',
    gap: '10px',
  },
  mobileSheetGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '10px',
  },
  mobileSheetLink: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    minWidth: 0,
    minHeight: '52px',
    padding: '12px 14px',
    borderRadius: radius.md,
    border: '1px solid rgba(67, 103, 124, 0.42)',
    backgroundColor: 'rgba(11, 20, 29, 0.7)',
    color: 'rgba(222, 235, 244, 0.96)',
    textDecoration: 'none',
    boxShadow: 'inset 0 1px 0 rgba(214, 236, 247, 0.05)',
    transitionProperty: 'transform, border-color, background-color, box-shadow',
    transitionDuration: '180ms',
    ':hover': {
      backgroundColor: 'rgba(17, 31, 42, 0.92)',
      borderColor: 'rgba(164, 205, 223, 0.5)',
      transform: 'translateY(-1px)',
    },
    ':active': {
      transform: 'translateY(1px) scale(0.99)',
    },
    ':focus-visible': {
      outline: '2px solid rgba(196, 227, 241, 0.72)',
      outlineOffset: '2px',
    },
  },
  mobileSheetLinkActive: {
    borderColor: 'rgba(170, 209, 227, 0.72)',
    background: 'linear-gradient(125deg, rgba(26, 53, 69, 0.92), rgba(14, 29, 39, 0.94))',
    boxShadow: '0 16px 30px rgba(4, 8, 12, 0.58)',
  },
  mobileSheetIcon: {
    display: 'inline-grid',
    placeItems: 'center',
    width: '36px',
    height: '36px',
    borderRadius: '12px',
    border: '1px solid rgba(143, 185, 204, 0.18)',
    backgroundColor: 'rgba(9, 17, 25, 0.84)',
    flex: '0 0 auto',
  },
  mobileDock: {
    position: 'relative',
    width: 'min(100%, 560px)',
    marginInline: 'auto',
    padding: '6px',
    borderTopLeftRadius: '22px',
    borderTopRightRadius: '22px',
    boxShadow: '0 -18px 40px rgba(4, 8, 12, 0.72)',
    overflow: 'hidden',
    background: 'linear-gradient(to top, rgba(10, 17, 24, 0.96), rgba(17, 29, 39, 0.88))',
    border: '1px solid rgba(34, 53, 68, 0.6)',
    backdropFilter: 'blur(18px)',
    '::before': {
      content: "''",
      position: 'absolute',
      inset: 0,
      borderRadius: '24px',
      border: '1px solid rgba(207, 230, 245, 0.08)',
      pointerEvents: 'none',
    },
  },
  mobileDockInner: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '6px',
  },
  mobileChip: {
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flex: '1 1 0%',
    minWidth: '72px',
    minHeight: '64px',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '16px',
    padding: '10px 6px 9px',
    backdropFilter: 'blur(10px)',
    backgroundColor: 'rgba(9, 19, 27, 0.74)',
    border: '1px solid rgba(67, 103, 124, 0.5)',
    color: colors.paper,
    textDecoration: 'none',
    boxShadow: 'inset 0 1px 0 rgba(214, 236, 247, 0.05)',
    transitionProperty: 'transform, background-color, border-color',
    transitionDuration: '300ms',
    ':hover': {
      backgroundColor: 'rgba(18, 35, 48, 0.84)',
      borderColor: 'rgba(164, 205, 223, 0.52)',
      transform: 'translateY(-1px)',
    },
    ':active': {
      transform: 'translateY(1px) scale(0.985)',
      backgroundColor: 'rgba(21, 39, 53, 0.94)',
    },
    ':focus-visible': {
      outline: '2px solid rgba(196, 227, 241, 0.78)',
      outlineOffset: '2px',
    },
  },
  mobileChipActive: {
    background: 'linear-gradient(125deg, rgba(26, 53, 69, 0.92), rgba(14, 29, 39, 0.94))',
    borderColor: 'rgba(170, 209, 227, 0.66)',
    boxShadow: '0 16px 30px rgba(4, 8, 12, 0.66)',
    '::after': {
      content: "''",
      position: 'absolute',
      inset: 0,
      border: '1px solid rgba(143, 185, 204, 0.35)',
      borderRadius: '20px',
      animationName: {
        default: 'navPulse',
      },
      animationDuration: '2.2s',
      animationTimingFunction: 'ease-in-out',
      animationIterationCount: 'infinite',
      pointerEvents: 'none',
    },
  },
  mobileMore: {
    flex: '0.95',
  },
  mobileLinkContent: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
  },
  mobileLabel: {
    fontSize: {
      default: '10px',
      '@media (min-width: 640px)': '11px',
    },
    fontWeight: 600,
    lineHeight: 1,
    letterSpacing: '0.01em',
    whiteSpace: 'nowrap',
  },
});
